<a href="https://colab.research.google.com/github/ideablast/NLPer_chatbot/blob/toram/base_pumsa_mecab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mecab Test

In [4]:
!pip install konlpy

In [5]:
! git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

fatal: destination path 'Mecab-ko-for-Google-Colab' already exists and is not an empty directory.


In [6]:
cd Mecab-ko-for-Google-Colab

/content/Mecab-ko-for-Google-Colab


In [7]:
! bash install_mecab-ko_on_colab190912.sh

Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2020-10-28 14:04:44--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.0, 18.205.93.2, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=9ba7ukzsUuwO5mPcRW%2BLNkKorsk%3D&Expires=1603894469&AWSAccessKeyId=AKIA6KOSE3BNJRRFUUX6&versionId=null&response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None [following]
--2020-10-28 14:04:44--  https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=9ba7ukzsUuwO5mPcRW%2BLNkKorsk%3D&Expires=1603894469&AW

In [8]:
from konlpy.tag import Mecab 
mecab = Mecab()
text = u"""이제 구글 코랩에서 Mecab-ko라이브러리 사용이 가능합니다. 읽어주셔서 감사합니다.""" 
nouns = mecab.pos(text)
# nouns = mecab(text) 
print(nouns)

[('이제', 'MAG'), ('구글', 'NNG'), ('코', 'NNG'), ('랩', 'NNG'), ('에서', 'JKB'), ('Mecab', 'SL'), ('-', 'SY'), ('ko', 'SL'), ('라이브러리', 'NNG'), ('사용', 'NNG'), ('이', 'JKS'), ('가능', 'NNG'), ('합니다', 'XSA+EF'), ('.', 'SF'), ('읽', 'VV'), ('어', 'EC'), ('주', 'VX'), ('셔서', 'EP+EC'), ('감사', 'NNG'), ('합니다', 'XSV+EF'), ('.', 'SF')]


In [9]:
from keras import models
from keras import layers
from keras import optimizers, losses, metrics
from keras import preprocessing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt, Mecab

In [10]:
#@title 기본 제목 텍스트
# 태그 단어
PAD = "<PADDING>"   # 패딩
STA = "<START>"     # 시작
END = "<END>"       # 끝
OOV = "<OOV>"       # 없는 단어(Out of Vocabulary)

# 태그 인덱스
PAD_INDEX = 0
STA_INDEX = 1
END_INDEX = 2
OOV_INDEX = 3

# 데이터 타입
ENCODER_INPUT  = 0
DECODER_INPUT  = 1
DECODER_TARGET = 2

# 한 문장에서 단어 시퀀스의 최대 개수
max_sequences = 30

# 임베딩 벡터 차원
embedding_dim = 100

# LSTM 히든레이어 차원
lstm_hidden_dim = 128

# 정규 표현식 필터
RE_FILTER = re.compile("[.,!?\"':;~()]")

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
wear_data = pd.read_csv("/content/drive/My Drive/wear.csv")
print(wear_data.shape)
customer = wear_data[wear_data.SPEAKER == "고객"].SENTENCE
store = wear_data[wear_data.SPEAKER == "점원"].SENTENCE
print(customer.shape, store.shape) # 질문의 개수와 답의 개수가 일치하지 않는다.

(15826, 20)
(8381,) (7445,)


In [13]:
prev = "고객"
store_arr = []
customer_arr = []
store_stc = ""
customer_stc = ""

for i in range(wear_data.shape[0]):
    if (prev == wear_data.iloc[i].SPEAKER):
        if prev == "점원":
             store_stc += (" "+wear_data.iloc[i].SENTENCE)
        else : 
            customer_stc += (" "+wear_data.iloc[i].SENTENCE)
            
    elif prev == "점원":
        store_arr.append(store_stc)
        customer_stc = wear_data.iloc[i].SENTENCE
        prev = "고객"
    else :
        customer_arr.append(customer_stc)
        store_stc = wear_data.iloc[i].SENTENCE
        prev = "점원"

print(len(store_arr))
print(len(customer_arr))
print(store_arr[-1])
print(customer_arr[-1]) # 자료 상에서 이후에는 계속 고객의 물음만 계속된다. 코드 레벨에서 이 부분은 빼게 구현했다. (stc는 만들어지지만 arr에 append 안하게 된다.)

7301
7301
요즘 파스텔 톤이 유행이에요
요즘 유행하는 색깔이 뭐예요?


In [14]:
question = []
answer = []
pumsa_question = []
pumsa_answer = []

for Q in customer_arr:
    question.append(Q.replace("[^\w]", " "))

for A in store_arr:
    answer.append(A.replace("[^\w]", " "))

len(question), len(answer)

(7301, 7301)

In [15]:
# 형태소분석 함수
def pos_tag(sentences):
    
    # KoNLPy 형태소분석기 설정
    # tagger = Okt()
    tagger = Mecab()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in sentences:
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [16]:
# 형태소분석 함수
def pumsa_tag(sentences):
    
    # KoNLPy 형태소분석기 설정
    # tagger = Okt()
    tagger = Mecab()
    
    # 문장 품사 변수 초기화
    pumsa_pos = []
    
    # 모든 문장 반복
    for sentence in sentences:
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        tmp_result = []
        tmp = []
        tmp = tagger.pos(sentence)
        for i in tmp:
            tmp_result.append(i[0]+'/'+i[1])

        tmp = " ".join(tmp_result)

        pumsa_pos.append(tmp)
        
    return pumsa_pos

In [17]:
print(pumsa_tag(question))

['신발/NNG 은/JX 여기/NP 있/VA 는/ETM 게/NNB+JKS 다예/NNG 요/VCP+EC', '230/SN 이/VCP 요/EC', '네/IC 봄/NNG 이/VCP 니까/EC 편하/VA 게/EC 신/VV 을/ETM 수/NNB 있/VV 는/ETM 거/NNB', '굽/NNG 좀/MAG 높/VA 은/ETM 거/NNB 없/VA 나요/EC', '언제/MAG 들어와요/VV+EF', '이거/NP 는/JX 가죽/NNG 이/VCP 에요/EF', '가죽/NNG 은/JX 얼마/NNG 예요/VCP+EF', '털/NNG 달린/VV+ETM 거/NNB 저거/NP 는/JX 사이즈/NNG 있/VA 어요/EF', '좀/MAG 크/VA 네/EF 또/MAG 안/MAG 들어와요/VV+EF', '가방/NNG 매/VV 는/ETM 거/NNB 보/VV 고/EC 있/VX 어요/EF', '가격/NNG 이/JKS 얼마/NNG 예요/VCP+EF', '가죽/NNG 으로/JKB 된/VV+ETM 거/NNB 는/JX 없/VA 어요/EF', '레자/NNG 는/JX 얼마/NNG 예요/VCP+EF', '이거/NP 는/JX 천/NNG 이/VCP 죠/EF', '이건/NP+JX 얼마/NNG 예요/VCP+EF', '이거/NP 끈/NNG 은/JX 따로/MAG 없/VA 어요/EF', '내일/NNG 은/JX 문/NNG 열/VV 어요/EF', '며칠/NNG 까지/JX 휴무/NNG 예요/VCP+EF', '여기/NP 마스크/NNG 는/JX 얼마/NNG 예요/VCP+EF', '이거/NP 나무/NNG 예요/VCP+EF 다/MAG 돌/NNG 인가요/VCP+EC', '이런/MM 건/NNB+JX 세트/NNG 로/JKB 팔/VV 아요/EC', '이건/NP+JX 뭐/NP 예요/VCP+EF', '제일/MAG 큰/VA+ETM 거/NNB 는/JX 얼마/NNG 인데요/VCP+EC', '스카프/NNG 좀/MAG 보/VV 려구요/EC', '실크/NNG 스카프/NNG 도/JX 봄/NNG 에/JKB 하/VV 나요/EC', '이거/NP 는/JX 뭐/NP 예요

In [18]:
# 형태소분석 수행
question = pos_tag(question)
answer = pos_tag(answer)
pumsa_question = pumsa_tag(question)
pumsa_answer = pumsa_tag(answer)

# 형태소분석으로 변환된 챗봇 데이터 출력
for i in range(5):
    print('Q : ' + question[i])
    print(pumsa_question[i])
    print('A : ' + answer[i])
    print(pumsa_answer[i])
    print()

Q : 신발 은 여기 있 는 게 다예 요
신발/NNG 은/JX 여기/NP 있/VA 는/ETM 게/NNB+JKS 다예/NNG 요/VCP+EC
A : 네 성인 이나 아동 다 있 어요 발 사이즈 몇 신 으세요
네/IC 성인/NNG 이나/NNG+JC 아동/NNG 다/MAG 있/VA 어요/EF 발/NNG 사이즈/NNG 몇/MM 신/VV 으세요/EC

Q : 230 이 요
230/SN 이/NR 요/NNG
A : 편하 게 신 을 수 있 는 거 찾 으세요
편하/VA 게/EC 신/VV 을/ETM 수/NNB 있/VV 는/ETM 거/NNB 찾/VV 으세요/EC

Q : 네 봄 이 니까 편하 게 신 을 수 있 는 거
네/IC 봄/NNG 이/VCP 니까/EC 편하/VA 게/EC 신/VV 을/ETM 수/NNB 있/VV 는/ETM 거/NNB
A : 이런 건 어떠세요 이런 거 도 신발 무척 편하 거든요
이런/MM 건/NNB+JX 어떠세요/VA+EP+EF 이런/MM 거/NNB 도/JX 신발/NNG 무척/MAG 편하/VA 거든요/EF

Q : 굽 좀 높 은 거 없 나요
굽/NNG 좀/MAG 높/VA 은/ETM 거/NNB 없/VA 나요/EC
A : 봄 상품 은 아직 어른 제품 이 많이 안 나왔 습니다
봄/NNG 상품/NNG 은/JX 아직/MAG 어른/NNG 제품/NNG 이/MM 많이/MAG 안/MAG 나왔/VV+EP 습니다/EF

Q : 언제 들어와요
언제/MAG 들어와요/VV+EF
A : 이번 주 지나 면 들어올 거 예요
이번/NNG 주/NNG 지나/VV 면/EC 들어올/VV+ETM 거/NNB 예요/VCP+EF



In [19]:
qustion = pumsa_question
answer = pumsa_answer

In [20]:
# 질문과 대답 문장들을 하나로 합침
sentences = []
sentences.extend(question)
sentences.extend(answer)

print(sentences)

words = []

# 단어들의 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)

# 길이가 0인 단어는 삭제
words = [word for word in words if len(word) > 0]

# 중복된 단어 삭제
words = list(set(words))

# 제일 앞에 태그 단어 삽입
words[:0] = [PAD, STA, END, OOV]

['신발 은 여기 있 는 게 다예 요', '230 이 요', '네 봄 이 니까 편하 게 신 을 수 있 는 거', '굽 좀 높 은 거 없 나요', '언제 들어와요', '이거 는 가죽 이 에요', '가죽 은 얼마 예요', '털 달린 거 저거 는 사이즈 있 어요', '좀 크 네 또 안 들어와요', '가방 매 는 거 보 고 있 어요', '가격 이 얼마 예요', '가죽 으로 된 거 는 없 어요', '레자 는 얼마 예요', '이거 는 천 이 죠', '이건 얼마 예요', '이거 끈 은 따로 없 어요', '내일 은 문 열 어요', '며칠 까지 휴무 예요', '여기 마스크 는 얼마 예요', '이거 나무 예요 다 돌 인가요', '이런 건 세트 로 팔 아요', '이건 뭐 예요', '제일 큰 거 는 얼마 인데요', '스카프 좀 보 려구요', '실크 스카프 도 봄 에 하 나요', '이거 는 뭐 예요', '여기 가격 은 그대로 파 시 는 거 예요', '착용 해 볼 수 있 어요', '이거 는 요즘 들어온 거 예요', '세탁 은 물세탁 되 죠', '지금 여기 있 는 게 다예 요', '몇 시 에 문 닫 아요', '일요일 도 하 세요', '스카프 있 어요', '이런 건 세탁 을 어떻 게 해요', '원단 은 뭐 예요', '얼마 인데요', '브로치 같 은 건 어디 있 나요', '이런 거 도 2 만 원 이 예요', '명품 이랑 똑같이 한 거 예요', '온누리 상품권 도 되 죠', '브로치 하 고 머리핀 하 고 보 려고요', '도자기 같 은 거 말 고 구슬 이나 진주 같 은 거 는 없 어요', '그건 흥미 없 고 안 에 하 면 안 떨어져요', '얼마 예요', '이 우산 은 얼마 인데요', '무겁 지 않 아요', '이렇게 다 는 거 맞 아요', '자석 은 다 3 만 원', '머리핀 종류 도 한 번 보여 주 세요 곱창 은 요새 안 나와요', '브로치 종류 도 있 어요', '스카프 도 없 어요', '이런 거 실크 입니까', '이런 거 는 뭐 라 그래요', '이런 거 는 얼마 예요', '이런 거 는 물세탁

In [21]:
print("손님과 점원의 말에서 사용된 총 단어의 수 :",len(words))

손님과 점원의 말에서 사용된 총 단어의 수 : 6015


In [22]:
# 단어 출력
words[:20]

['<PADDING>',
 '<START>',
 '<END>',
 '<OOV>',
 '면서',
 '소재/NNG',
 '아무',
 '스타일',
 '줄여/VV+EC',
 '한/XSV+ETM',
 '모피',
 '수천/NR',
 '왼쪽',
 '조회/NNG',
 '알',
 '비',
 '용액/NNG',
 '돼야/VV+EC',
 '기울일/VV+ETM',
 '버건']

In [23]:
# 단어와 인덱스의 딕셔너리 생성
word_to_index = {word: index for index, word in enumerate(words)}
index_to_word = {index: word for index, word in enumerate(words)}

In [24]:
word_to_index

{'<PADDING>': 0,
 '<START>': 1,
 '<END>': 2,
 '<OOV>': 3,
 '면서': 4,
 '소재/NNG': 5,
 '아무': 6,
 '스타일': 7,
 '줄여/VV+EC': 8,
 '한/XSV+ETM': 9,
 '모피': 10,
 '수천/NR': 11,
 '왼쪽': 12,
 '조회/NNG': 13,
 '알': 14,
 '비': 15,
 '용액/NNG': 16,
 '돼야/VV+EC': 17,
 '기울일/VV+ETM': 18,
 '버건': 19,
 '허리': 20,
 '현금가/NNG': 21,
 '울/NNG': 22,
 '상관/NNG': 23,
 '황금': 24,
 '이/JKC': 25,
 '아요': 26,
 '어떠신가요/VA+EP+EC': 27,
 '와서': 28,
 '불가': 29,
 '드신/VV+EP+ETM': 30,
 '베스트': 31,
 '꽂/VV': 32,
 '보여줘': 33,
 '전량/NNG': 34,
 '43000/SN': 35,
 '트랩': 36,
 '돼/VV+EC': 37,
 '있': 38,
 '항상/MAG': 39,
 '같이/MAG': 40,
 '색/NNG': 41,
 '60000/SN': 42,
 '와이프': 43,
 '세사/NNG': 44,
 '대해서': 45,
 '미색': 46,
 '면서/EC': 47,
 '잘': 48,
 '볼래요': 49,
 '요새/NNG': 50,
 '플래티넘/NNP': 51,
 '총/MM': 52,
 '준/VV+ETM': 53,
 '위주/NNG': 54,
 '울/NP': 55,
 '아닌/VCN+ETM': 56,
 '아야/EC': 57,
 '전공/NNG': 58,
 '두껍/VA': 59,
 '계좌': 60,
 '칠만': 61,
 '주차장': 62,
 '순/NNG': 63,
 '불편': 64,
 '봐/VX+EC': 65,
 '연두색/NNG': 66,
 '무/NNBC': 67,
 '제거/NNG': 68,
 '학년': 69,
 '며칠': 70,
 '기장': 71,
 '라면/VCP+EC': 

In [25]:
# 문장을 인덱스로 변환
def convert_text_to_index(sentences, vocabulary, type): 
    
    sentences_index = []
    
    # 모든 문장에 대해서 반복
    for sentence in sentences:
        sentence_index = []
        
        # 디코더 입력일 경우 맨 앞에 START 태그 추가
        if type == DECODER_INPUT:
            sentence_index.extend([vocabulary[STA]])
        
        # 문장의 단어들을 띄어쓰기로 분리
        for word in sentence.split():
            if vocabulary.get(word) is not None:
                # 사전에 있는 단어면 해당 인덱스를 추가
                sentence_index.extend([vocabulary[word]])
            else:
                # 사전에 없는 단어면 OOV 인덱스를 추가
                sentence_index.extend([vocabulary[OOV]])

        # 최대 길이 검사
        if type == DECODER_TARGET:
            # 디코더 목표일 경우 맨 뒤에 END 태그 추가
            if len(sentence_index) >= max_sequences:
                sentence_index = sentence_index[:max_sequences-1] + [vocabulary[END]]
            else:
                sentence_index += [vocabulary[END]]
        else:
            if len(sentence_index) > max_sequences:
                sentence_index = sentence_index[:max_sequences]
            
        # 최대 길이에 없는 공간은 패딩 인덱스로 채움
        sentence_index += (max_sequences - len(sentence_index)) * [vocabulary[PAD]]
        
        # 문장의 인덱스 배열을 추가
        sentences_index.append(sentence_index)

    return np.asarray(sentences_index)

In [26]:
# 인코더 입력 인덱스 변환
x_encoder = convert_text_to_index(question, word_to_index, ENCODER_INPUT)

# 첫 번째 인코더 입력 출력 (신발 은 여기 있는 게 다예 요)
print(question[2])
print(x_encoder[2])
print(x_encoder[2].shape[0])
x_encoder[2].reshape(1, x_encoder[2].shape[0])


네 봄 이 니까 편하 게 신 을 수 있 는 거
[3463 2157 4821 2688 3530 1097 1396 4588 2489   38 3809 3103    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
30


array([[3463, 2157, 4821, 2688, 3530, 1097, 1396, 4588, 2489,   38, 3809,
        3103,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]])

In [27]:
# 디코더 입력 인덱스 변환
x_decoder = convert_text_to_index(answer, word_to_index, DECODER_INPUT)

# 첫 번째 디코더 입력 출력 (<START> 신발 은 여기 있는 게 다예 요)
print(question[0])
x_decoder[0]


신발 은 여기 있 는 게 다예 요


array([   1,  141,  437, 1073, 1916, 5584, 1796, 1045,  157, 3539, 1998,
       1292, 5959,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [28]:
# 디코더 목표 인덱스 변환
y_decoder = convert_text_to_index(answer, word_to_index, DECODER_TARGET)

# 첫 번째 디코더 입력 출력 (신발 은 여기 있는 게 다예 요 <END>)
print(question[0])
y_decoder[0]


신발 은 여기 있 는 게 다예 요


array([ 141,  437, 1073, 1916, 5584, 1796, 1045,  157, 3539, 1998, 1292,
       5959,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [29]:
# 원핫인코딩 초기화
one_hot_data = np.zeros((len(y_decoder), max_sequences, len(words)))

# 디코더 목표를 원핫인코딩으로 변환
# 학습시 입력은 인덱스이지만, 출력은 원핫인코딩 형식임
for i, sequence in enumerate(y_decoder):
    for j, index in enumerate(sequence):
        one_hot_data[i, j, index] = 1

# 디코더 목표 설정
y_decoder = one_hot_data

# 첫 번째 디코더 목표 출력
y_decoder[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

# 모델 생성

In [30]:
#--------------------------------------------
# 훈련 모델 인코더 정의
#--------------------------------------------

# 입력 문장의 인덱스 시퀀스를 입력으로 받음
encoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
encoder_outputs = layers.Embedding(len(words), embedding_dim)(encoder_inputs)

# return_state가 True면 상태값 리턴
# LSTM은 state_h(hidden state)와 state_c(cell state) 2개의 상태 존재
encoder_outputs, state_h, state_c = layers.LSTM(lstm_hidden_dim,
                                                return_state=True)(encoder_outputs)

# 히든 상태와 셀 상태를 하나로 묶음
encoder_states = [state_h, state_c]

#--------------------------------------------
# 훈련 모델 디코더 정의
#--------------------------------------------

# 목표 문장의 인덱스 시퀀스를 입력으로 받음
decoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
decoder_embedding = layers.Embedding(len(words), embedding_dim)
decoder_outputs = decoder_embedding(decoder_inputs)

# 인코더와 달리 return_sequences를 True로 설정하여 모든 타임 스텝 출력값 리턴
# 모든 타임 스텝의 출력값들을 다음 레이어의 Dense()로 처리하기 위함
decoder_lstm = layers.LSTM(lstm_hidden_dim,
                           return_state=True,
                           return_sequences=True)

# initial_state를 인코더의 상태로 초기화
decoder_outputs, _, _ = decoder_lstm(decoder_outputs,
                                     initial_state=encoder_states)

# 단어의 개수만큼 노드의 개수를 설정하여 원핫 형식으로 각 단어 인덱스를 출력
decoder_dense = layers.Dense(len(words), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)



#--------------------------------------------
# 훈련 모델 정의
#--------------------------------------------

# 입력과 출력으로 함수형 API 모델 생성
model = models.Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 학습 방법 설정
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])    

In [31]:
#--------------------------------------------
#  예측 모델 인코더 정의
#--------------------------------------------

# 훈련 모델의 인코더 상태를 사용하여 예측 모델 인코더 설정
encoder_model = models.Model(encoder_inputs, encoder_states)

#--------------------------------------------
# 예측 모델 디코더 정의
#--------------------------------------------

# 예측시에는 훈련시와 달리 타임 스텝을 한 단계씩 수행
# 매번 이전 디코더 상태를 입력으로 받아서 새로 설정
decoder_state_input_h = layers.Input(shape=(lstm_hidden_dim,))
decoder_state_input_c = layers.Input(shape=(lstm_hidden_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]    

# 임베딩 레이어
decoder_outputs = decoder_embedding(decoder_inputs)

# LSTM 레이어
decoder_outputs, state_h, state_c = decoder_lstm(decoder_outputs,
                                                 initial_state=decoder_states_inputs)

# 히든 상태와 셀 상태를 하나로 묶음
decoder_states = [state_h, state_c]

# Dense 레이어를 통해 원핫 형식으로 각 단어 인덱스를 출력
decoder_outputs = decoder_dense(decoder_outputs)

# 예측 모델 디코더 설정
decoder_model = models.Model([decoder_inputs] + decoder_states_inputs,
                      [decoder_outputs] + decoder_states)

In [32]:
# 인덱스를 문장으로 변환
def convert_index_to_text(indexs, vocabulary): 
    
    sentence = ''
    
    # 모든 문장에 대해서 반복
    for index in indexs:
        if index == END_INDEX:
            # 종료 인덱스면 중지
            break;
        if vocabulary.get(index) is not None:
            # 사전에 있는 인덱스면 해당 단어를 추가
            sentence += vocabulary[index]
        else:
            # 사전에 없는 인덱스면 OOV 단어를 추가
            sentence.extend([vocabulary[OOV_INDEX]])
            
        # 빈칸 추가
        sentence += ' '

    return sentence

In [33]:
x_encoder[2].reshape(1, x_encoder[2].shape[0])

array([[3463, 2157, 4821, 2688, 3530, 1097, 1396, 4588, 2489,   38, 3809,
        3103,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]])

In [1]:
# 에폭 반복
for epoch in range(1):
    print('Total Epoch :', epoch + 1)

    # 훈련 시작
    history = model.fit([x_encoder, x_decoder],
                        y_decoder,
                        epochs=1,
                        batch_size=64,
                        verbose=1)
    # '네 봄 이니까 편하게 신 을 수 있는 거'에 대한 대답
    input_encoder = x_encoder[2].reshape(1, x_encoder[2].shape[0])
    input_decoder = x_decoder[2].reshape(1, x_decoder[2].shape[0])
    results = model.predict([input_encoder, input_decoder])
    
    # 결과의 원핫인코딩 형식을 인덱스로 변환
    # 1축을 기준으로 가장 높은 값의 위치를 구함
    indexs = np.argmax(results[0], 1)
    
    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
    print(sentence)
    print()

Total Epoch : 1


NameError: ignored

# 문장 생성

In [ ]:
# 예측을 위한 입력 생성
def make_predict_input(sentence):

    sentences = []
    sentences.append(sentence)
    sentences = pos_tag(sentences)
    input_seq = convert_text_to_index(sentences, word_to_index, ENCODER_INPUT)
    
    return input_seq

In [ ]:
# 텍스트 생성
def generate_text(input_seq):
    
    # 입력을 인코더에 넣어 마지막 상태 구함
    states = encoder_model.predict(input_seq)

    # 목표 시퀀스 초기화
    target_seq = np.zeros((1, 1))
    
    # 목표 시퀀스의 첫 번째에 <START> 태그 추가
    target_seq[0, 0] = STA_INDEX
    
    # 인덱스 초기화
    indexs = []
    
    # 디코더 타임 스텝 반복
    while 1:
        # 디코더로 현재 타임 스텝 출력 구함
        # 처음에는 인코더 상태를, 다음부터 이전 디코더 상태로 초기화
        decoder_outputs, state_h, state_c = decoder_model.predict(
                                                [target_seq] + states)

        # 결과의 원핫인코딩 형식을 인덱스로 변환
        index = np.argmax(decoder_outputs[0, 0, :])
        indexs.append(index)
        
        # 종료 검사
        if index == END_INDEX or len(indexs) >= max_sequences:
            break

        # 목표 시퀀스를 바로 이전의 출력으로 설정
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = index
        
        # 디코더의 이전 상태를 다음 디코더 예측에 사용
        states = [state_h, state_c]

    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
        
    return sentence

In [ ]:
# 문장을 인덱스로 변환
input_seq = make_predict_input('이 티셔츠 사이즈 있나요')
input_seq


In [ ]:
# 예측 모델로 텍스트 생성
sentence = generate_text(input_seq)
sentence


In [ ]:
# for train data predict
for seq_index in range(0,100):

  print("고객 : ",question[seq_index])
  print("정답점원 :",answer[seq_index])
  print("AI점원 :",generate_text(make_predict_input(question[seq_index])))
  print("\n")