<a href="https://colab.research.google.com/github/ideablast/NLPer_chatbot/blob/toram/Chatbot_Transformer_okt_svm%EC%8B%9C%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 1.4MB/s 
     |████████████████████████████████| 92kB 3.6MB/s 
     |████████████████████████████████| 460kB 44.4MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0


## Import

In [ ]:
from keras import models
from keras import layers
from keras import optimizers, losses, metrics
from keras import preprocessing

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt

## Hyperparameter

In [ ]:
# 태그 단어
PAD = "<PADDING>"   # 패딩
STA = "<START>"     # 시작
END = "<END>"       # 끝
OOV = "<OOV>"       # 없는 단어(Out of Vocabulary)

# 태그 인덱스
PAD_INDEX = 0
STA_INDEX = 1
END_INDEX = 2
OOV_INDEX = 3

# 데이터 타입
ENCODER_INPUT  = 0
DECODER_INPUT  = 1
DECODER_TARGET = 2

# Hyper-parameters
NUM_LAYERS = 2
D_MODEL = 256 ##word embedding dim
NUM_HEADS = 8 ## D_Model % NUM_HEADS == 0이 되야하므로...
UNITS = 512
DROPOUT = 0.1
EPOCHS = 50
# for data pipelining
BATCH_SIZE = 64
BUFFER_SIZE = 1000

VOCAB_SIZE = 0 # 후에 len(words) 로 바뀜.

# 한 문장에서 단어 시퀀스의 최대 개수
max_sequences = 30

# 정규 표현식 필터
RE_FILTER = re.compile("[\"':;~()]")

## Data Load & Preprocessing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
wear_data = pd.read_csv("/content/drive/My Drive/wear.csv")
print(wear_data.shape)
customer = wear_data[wear_data.SPEAKER == "고객"].SENTENCE
store = wear_data[wear_data.SPEAKER == "점원"].SENTENCE
print(customer.shape, store.shape) # 질문의 개수와 답의 개수가 일치하지 않는다.

(15826, 20)
(8381,) (7445,)


In [ ]:
prev = "고객"
store_arr = []
customer_arr = []
store_stc = ""
customer_stc = ""

for i in range(wear_data.shape[0]):
    if (prev == wear_data.iloc[i].SPEAKER):
        if prev == "점원":
             store_stc += (" "+wear_data.iloc[i].SENTENCE)
        else : 
             customer_stc += (" "+wear_data.iloc[i].SENTENCE)
            
    elif prev == "점원":
        store_arr.append(store_stc)
        customer_stc = wear_data.iloc[i].SENTENCE
        prev = "고객"
    else :
        customer_arr.append(customer_stc)
        store_stc = wear_data.iloc[i].SENTENCE
        prev = "점원"

print(len(store_arr))
print(len(customer_arr))
print(store_arr[-1])
print(customer_arr[-1]) # 자료 상에서 이후에는 계속 고객의 물음만 계속된다. 코드 레벨에서 이 부분은 빼게 구현했다. (stc는 만들어지지만 arr에 append 안하게 된다.)

7301
7301
요즘 파스텔 톤이 유행이에요
요즘 유행하는 색깔이 뭐예요?


In [ ]:
question = []
answer = []

for Q in customer_arr:
    question.append(Q.replace("[^\w]", " "))

for A in store_arr:
    answer.append(A.replace("[^\w]", " "))

len(question), len(answer)

(7301, 7301)

In [ ]:
# 형태소분석 함수
def pos_tag(sentences):
    
    # KoNLPy 형태소분석기 설정
    tagger = Okt()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in sentences:
        # [\"':;~()] 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [ ]:
# 형태소분석 수행
question = pos_tag(question)
answer = pos_tag(answer)

# 형태소분석으로 변환된 챗봇 데이터 출력
for i in range(5):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()


Q : 신발 은 여기 있는 게 다예 요 ?
A : 네 성인 이나 아동 다 있어요 발 사이즈 몇 신으세요 ?

Q : 230 이요
A : 편하게 신 을 수 있는 거 찾으세요 ?

Q : 네 봄 이니까 편하게 신 을 수 있는 거
A : 이런 건 어떠세요 ? 이런 거도 신발 무척 편하거든요

Q : 굽 좀 높은 거 없나요 ?
A : 봄 상품 은 아직 어른 제품 이 많이 안 나왔습니다

Q : 언제 들어와요 ?
A : 이번 주 지나면 들어올 거 예요



In [ ]:
# 질문과 대답 문장들을 하나로 합침
sentences = []
sentences.extend(question)
sentences.extend(answer)

words = []

# 단어들의 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)

# 길이가 0인 단어는 삭제
words = [word for word in words if len(word) > 0]

# 중복된 단어 삭제
words = list(set(words))

# 제일 앞에 태그 단어 삽입
words[:0] = [PAD, STA, END, OOV]

In [ ]:
VOCAB_SIZE = len(words)
print("손님과 점원의 말에서 사용된 총 단어의 수 :",len(words))

손님과 점원의 말에서 사용된 총 단어의 수 : 6409


In [ ]:
# 단어와 인덱스의 딕셔너리 생성
word_to_index = {word: index for index, word in enumerate(words)}
index_to_word = {index: word for index, word in enumerate(words)}

In [ ]:
# 문장을 인덱스로 변환
def convert_text_to_index(sentences, vocabulary, type): 
    
    sentences_index = []
    
    # 모든 문장에 대해서 반복
    for sentence in sentences:
        sentence_index = []
        
        # 디코더 입력일 경우 맨 앞에 START 태그 추가
        if type == DECODER_INPUT:
            sentence_index.extend([vocabulary[STA]])
        
        # 문장의 단어들을 띄어쓰기로 분리
        for word in sentence.split():
            if vocabulary.get(word) is not None:
                # 사전에 있는 단어면 해당 인덱스를 추가
                sentence_index.extend([vocabulary[word]])
            else:
                # 사전에 없는 단어면 OOV 인덱스를 추가
                sentence_index.extend([vocabulary[OOV]])

        # 최대 길이 검사
        if type == DECODER_TARGET:
            # 디코더 목표일 경우 맨 뒤에 END 태그 추가
            if len(sentence_index) >= max_sequences:
                sentence_index = sentence_index[:max_sequences-1] + [vocabulary[END]]
            else:
                sentence_index += [vocabulary[END]]
        else:
            if len(sentence_index) > max_sequences:
                sentence_index = sentence_index[:max_sequences]
            
        # 최대 길이에 없는 공간은 패딩 인덱스로 채움
        sentence_index += (max_sequences - len(sentence_index)) * [vocabulary[PAD]]
        
        # 문장의 인덱스 배열을 추가
        sentences_index.append(sentence_index)

    return np.asarray(sentences_index)

In [ ]:
# 인코더 입력 인덱스 변환
x_encoder = convert_text_to_index(question, word_to_index, ENCODER_INPUT)

# 첫 번째 인코더 입력 출력 (신발 은 여기 있는 게 다예 요)
print(question[0])
x_encoder[0]


신발 은 여기 있는 게 다예 요 ?


array([4371, 2130, 2183, 2079, 1961, 3255, 2511, 4923,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [ ]:
# 디코더 입력 인덱스 변환
x_decoder = convert_text_to_index(answer, word_to_index, DECODER_INPUT)

# 첫 번째 디코더 입력 출력 (<START> 신발 은 여기 있는 게 다예 요)
print(question[0])
x_decoder[0]


신발 은 여기 있는 게 다예 요 ?


array([   1, 3824, 1065, 6038, 3033, 6040, 4593, 6096, 2148, 1116, 2222,
       4923,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [ ]:
# 디코더 목표 인덱스 변환
y_decoder = convert_text_to_index(answer, word_to_index, DECODER_TARGET)

# 첫 번째 디코더 입력 출력 (신발 은 여기 있는 게 다예 요 <END>)
print(question[0])
y_decoder[0]


신발 은 여기 있는 게 다예 요 ?


array([3824, 1065, 6038, 3033, 6040, 4593, 6096, 2148, 1116, 2222, 4923,
          2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

## Transformer

In [ ]:
# decoder inputs use the previous target as input
dataset = tf.data.Dataset.from_tensor_slices((
    {
        'inputs': x_encoder,
        'dec_inputs': x_decoder
    },
    {
        'outputs': y_decoder
    },
))

dataset = dataset.cache()
dataset = dataset.shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [ ]:
dataset

<PrefetchDataset shapes: ({inputs: (None, 30), dec_inputs: (None, 30)}, {outputs: (None, 30)}), types: ({inputs: tf.int64, dec_inputs: tf.int64}, {outputs: tf.int64})>

$$\Large{Attention(Q, K, V) = softmax_k(\frac{QK^T}{\sqrt{d_k}}) V} $$

In [ ]:
## scaled dot product Attention
def scaled_dot_product_attention(query, key, value, mask):
  matmul_qk = tf.matmul(query, key, transpose_b=True) # QK^T

  depth = tf.cast(tf.shape(key)[-1], tf.float32)
  logits = matmul_qk / tf.math.sqrt(depth) #  QK^T / sqrt(d_k)

  if mask is not None:
    logits += (mask * -1e9) # zero padding token softmax 결과가 0이 나오도록
  
  attention_weights = tf.nn.softmax(logits, axis = -1) # softmax(QK^T / sqrt(d_k))

  output = tf.matmul(attention_weights, value) # softmax(QK^T / sqrt(d_k)) * V

  return output

In [ ]:
## multi-head attention
## each head need (scaled_dot_product_attention)
class MultiHeadAttention(tf.keras.layers.Layer):
  def __init__(self, d_model, num_heads, name="multi_head_attention"):
    super(MultiHeadAttention, self).__init__(name=name)
    self.num_heads = num_heads
    self.d_model = d_model

    assert d_model % self.num_heads == 0 # 128,8

    self.depth = d_model // self.num_heads

    self.query_dense = tf.keras.layers.Dense(units=d_model)
    self.key_dense = tf.keras.layers.Dense(units=d_model)
    self.value_dense = tf.keras.layers.Dense(units=d_model)

    self.dense = tf.keras.layers.Dense(units=d_model)
  
  def split_heads(self, inputs, batch_size):
    inputs = tf.reshape(inputs, shape=(batch_size,-1,self.num_heads, self.depth))
    return tf.transpose(inputs, perm=[0, 2, 1, 3]) ##????
  
  def call(self, inputs):
    query, key, value, mask = inputs['query'], inputs['key'], inputs['value'], inputs['mask']
    batch_size = tf.shape(query)[0]

    #linear
    query = self.query_dense(query)
    key = self.key_dense(key)
    value = self.value_dense(value)

    #split heads
    query = self.split_heads(query, batch_size)
    key = self.split_heads(key, batch_size)
    value = self.split_heads(value, batch_size)

    #scaled dot-product attention
    scaled_attention = scaled_dot_product_attention(query, key, value, mask)
    scaled_attention = tf.transpose(scaled_attention, perm=[0, 2, 1, 3])

    #concatenation of heads
    concat_attention = tf.reshape(scaled_attention, (batch_size, -1, self.d_model))

    #final linear
    outputs = self.dense(concat_attention)

    return outputs

In [ ]:
def create_padding_mask(x):
  mask = tf.cast(tf.math.equal(x, 0), tf.float32)
  # (batch_size, 1, 1, sequence length)
  return mask[:, tf.newaxis, tf.newaxis, :]

In [ ]:
print(create_padding_mask(tf.constant([[1, 2, 0, 3, 0], [0, 0, 0, 4, 5]])))

tf.Tensor(
[[[[0. 0. 1. 0. 1.]]]


 [[[1. 1. 1. 0. 0.]]]], shape=(2, 1, 1, 5), dtype=float32)


In [ ]:
# it handle mask future tokens in a sequence used decoder. and mask pad tokens
def create_look_ahead_mask(x):
  seq_len = tf.shape(x)[1]
  look_ahead_mask = 1 - tf.linalg.band_part(tf.ones((seq_len, seq_len)), -1, 0)
  padding_mask = create_padding_mask(x)
  return tf.maximum(look_ahead_mask, padding_mask)

In [ ]:
print(create_look_ahead_mask(tf.constant([[1, 2, 0, 4, 5]])))

tf.Tensor(
[[[[0. 1. 1. 1. 1.]
   [0. 0. 1. 1. 1.]
   [0. 0. 1. 1. 1.]
   [0. 0. 1. 0. 1.]
   [0. 0. 1. 0. 0.]]]], shape=(1, 1, 5, 5), dtype=float32)


Positional encoding

since we don't use any rnn, cnn, positional encoding give model position information of words in sentence.

positional encoding vector is added to embedding vector

$$\Large{PE_{(pos, 2i)} = sin(pos / 10000^{2i / d_{model}})} $$
$$\Large{PE_{(pos, 2i+1)} = cos(pos / 10000^{2i / d_{model}})} $$

In [ ]:
class PositionalEncoding(tf.keras.layers.Layer):
  def __init__(self, position, d_model):
    super(PositionalEncoding, self).__init__()
    self.pos_encoding = self.positional_encoding(position, d_model)
  
  def get_angles(self, position, i, d_model):
    angles = 1 / tf.pow(10000, (2 * (i // 2)) / tf.cast(d_model, tf.float32))
    return position * angles #pos/10000^(2i/d_model)

  def positional_encoding(self, position, d_model):
    angle_rads = self.get_angles(
        position = tf.range(position, dtype=tf.float32)[:, tf.newaxis],
        i = tf.range(d_model, dtype=tf.float32)[tf.newaxis, :],
        d_model = d_model)
    sines = tf.math.sin(angle_rads[:, 0::2])
    cosines = tf.math.cos(angle_rads[:, 1::2])

    pos_encoding = tf.concat([sines, cosines], axis=-1)
    pos_encoding = pos_encoding[tf.newaxis, ...]
    return tf.cast(pos_encoding, tf.float32)
  
  def call(self, inputs):
    return inputs + self.pos_encoding[:, :tf.shape(inputs)[1], :]

### Encoder Layer
1. Multi-head attention (with padding mask)
2. 2 dense layers followed by dropout

also has residual connection followd by a layer normalization.

In [ ]:
def encoder_layer(units, d_model, num_heads, dropout, name="encoder_layer"):
  inputs = tf.keras.Input(shape=(None, d_model), name="inputs")
  padding_mask = tf.keras.Input(shape=(1, 1, None), name="padding_mask")

  attention = MultiHeadAttention(
      d_model, num_heads, name="attention")({
          'query':inputs,
          'key':inputs,
          'value':inputs,
          'mask':padding_mask
      })
  attention = tf.keras.layers.Dropout(rate=dropout)(attention)
  attention = tf.keras.layers.LayerNormalization(epsilon=1e-6)(inputs + attention)

  outputs = tf.keras.layers.Dense(units=units, activation='relu')(attention)
  outputs = tf.keras.layers.Dense(units=d_model)(outputs)
  outputs = tf.keras.layers.Dropout(rate=dropout)(outputs)
  outputs = tf.keras.layers.LayerNormalization(epsilon=1e-6)(attention + outputs)

  return tf.keras.Model(inputs=[inputs, padding_mask], outputs=outputs, name=name)

### Encoder
1. Input Embedding
2. Positional Encoding
3. `num_layers` encoder layers

Embedding + positional encoding : input

going encoder layers.

output going decoder

In [ ]:
def encoder(vocab_size,
            num_layers,
            units,
            d_model,
            num_heads,
            dropout,
            name="encoder"):
  inputs = tf.keras.Input(shape=(None,), name="inputs")
  padding_mask = tf.keras.Input(shape=(1, 1, None), name="padding_mask")

  embeddings = tf.keras.layers.Embedding(vocab_size, d_model)(inputs)
  embeddings *= tf.math.sqrt(tf.cast(d_model, tf.float32))
  embeddings = PositionalEncoding(vocab_size, d_model)(embeddings)#??왜 vocab_size가 들어가지?

  outputs = tf.keras.layers.Dropout(rate=dropout)(embeddings)

  for i in range(num_layers):
    outputs = encoder_layer(
        units = units,
        d_model = d_model,
        num_heads = num_heads,
        dropout = dropout,
        name = "encoder_layer_{}".format(i),
    )([outputs, padding_mask])
  
  return tf.keras.Model(
      inputs = [inputs, padding_mask], outputs = outputs, name=name)

### Decoder Layer
1. Masked multi-head attention (with look ahead mask and padding mask)
2. Multi-head attention (with padding mask). `value` and `key` is from encoder output. `query` is from Multi-head attention layer output
3. 2 dense layers followed by dropout

also has residual connection followd by a layer normalization.

In [ ]:
def decoder_layer(units, d_model, num_heads, dropout, name="decoder_layer"):
  inputs = tf.keras.Input(shape=(None, d_model), name="inputs")
  enc_outputs = tf.keras.Input(shape=(None, d_model), name="encoder_outputs")
  look_ahead_mask = tf.keras.Input(shape=(1,None,None), name="look_ahead_mask")
  padding_mask = tf.keras.Input(shape=(1,1,None), name="padding_mask")

  attention1 = MultiHeadAttention(
      d_model, num_heads, name="attention_1")(inputs={
          'query' : inputs,
          'key' : inputs,
          'value' : inputs,
          'mask' : look_ahead_mask
      })
  attention1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)(attention1 + inputs)

  attention2 = MultiHeadAttention(
      d_model, num_heads, name="attention_2")(inputs={
          'query' : attention1,
          'key' : enc_outputs,
          'value' : enc_outputs,
          'mask' : padding_mask
      })
  attention2 = tf.keras.layers.Dropout(rate=dropout)(attention2)
  attention2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)(attention2 + attention1)

  outputs = tf.keras.layers.Dense(units=units, activation='relu')(attention2)
  outputs = tf.keras.layers.Dense(units=d_model)(outputs)
  outputs = tf.keras.layers.Dropout(rate=dropout)(outputs)
  outputs = tf.keras.layers.LayerNormalization(epsilon=1e-6)(outputs + attention2)

  return tf.keras.Model(
      inputs = [inputs, enc_outputs, look_ahead_mask, padding_mask],
      outputs = outputs,
      name = name)

### Decoder
1. output Embedding
2. Positional Encoding
3. `num_layers` decoder layers

Embedding + positional encoding : input (target)

going decoder layers.

output going final linear layer

In [ ]:
def decoder(vocab_size,
            num_layers,
            units,
            d_model,
            num_heads,
            dropout,
            name="decoder"):
  inputs = tf.keras.Input(shape=(None,), name="inputs")
  enc_outputs = tf.keras.Input(shape=(None, d_model), name="encoder_outputs")
  look_ahead_mask = tf.keras.Input(shape=(1,None,None), name="look_ahead_mask")
  padding_mask = tf.keras.Input(shape=(1,1,None), name='padding_mask')

  embeddings = tf.keras.layers.Embedding(vocab_size, d_model)(inputs)
  embeddings *= tf.math.sqrt(tf.cast(d_model, tf.float32))
  embeddings = PositionalEncoding(vocab_size, d_model)(embeddings)

  outputs = tf.keras.layers.Dropout(rate=dropout)(embeddings)

  for i in range(num_layers):
    outputs = decoder_layer(
        units = units,
        d_model = d_model,
        num_heads = num_heads,
        dropout = dropout,
        name = "decoder_layer_{}".format(i),
    )(inputs = [outputs, enc_outputs, look_ahead_mask, padding_mask])
  
  return tf.keras.Model(
      inputs = [inputs, enc_outputs, look_ahead_mask, padding_mask],
      outputs = outputs,
      name = name)

### Transformer
1. encoder
2. decoder
3. final linear layer

In [ ]:
def transformer(vocab_size,
                num_layers,
                units,
                d_model,
                num_heads,
                dropout,
                name="transformer"):
  inputs = tf.keras.Input(shape=(None,), name="inputs")
  dec_inputs = tf.keras.Input(shape=(None,), name="dec_inputs")

  enc_padding_mask = tf.keras.layers.Lambda(
      create_padding_mask, output_shape=(1,1,None),
      name="enc_padding_mask")(inputs)
  
  #mask future tokens for decoder inputs at 1st attention block
  look_ahead_mask = tf.keras.layers.Lambda(
      create_look_ahead_mask, output_shape=(1,None,None),
      name="look_ahead_mask")(dec_inputs)
  
  #mask encoder outputs for the 2nd attention block
  dec_padding_mask = tf.keras.layers.Lambda(
      create_padding_mask, output_shape=(1,1,None),
      name="dec_padding_mask")(inputs)
  
  enc_outputs = encoder(
      vocab_size=vocab_size,
      num_layers=num_layers,
      units=units,
      d_model=d_model,
      num_heads=num_heads,
      dropout=dropout,
  )(inputs=[inputs, enc_padding_mask])

  dec_outputs = decoder(
      vocab_size=vocab_size,
      num_layers=num_layers,
      units=units,
      d_model=d_model,
      num_heads=num_heads,
      dropout=dropout,
  )(inputs=[dec_inputs, enc_outputs, look_ahead_mask, dec_padding_mask])

  outputs = tf.keras.layers.Dense(units=vocab_size, name="outputs")(dec_outputs)

  return tf.keras.Model(inputs=[inputs, dec_inputs], outputs=outputs, name=name)

## 모델 생성

In [ ]:
tf.keras.backend.clear_session()

model = transformer(
    vocab_size=VOCAB_SIZE,
    num_layers=NUM_LAYERS,
    units=UNITS,
    d_model=D_MODEL,
    num_heads=NUM_HEADS,
    dropout=DROPOUT)

### Loss function
since target sequences are padded, deal this.

In [ ]:
def loss_function(y_true, y_pred):
  y_true = tf.reshape(y_true, shape=(-1, max_sequences))

  loss = tf.keras.losses.SparseCategoricalCrossentropy(
      from_logits=True, reduction='none')(y_true, y_pred)
  
  mask = tf.cast(tf.not_equal(y_true,0), tf.float32)
  loss = tf.multiply(loss, mask)

  return tf.reduce_mean(loss)

### Custom learning rate
use Adam optimizer with custom learning rate
$$\Large{lrate = d_{model}^{-0.5} * min(step{\_}num^{-0.5}, step{\_}num * warmup{\_}steps^{-1.5})}$$

In [ ]:
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):

  def __init__(self, d_model, warmup_steps=4000):
    super(CustomSchedule, self).__init__()

    self.d_model = d_model
    self.d_model = tf.cast(self.d_model, tf.float32)

    self.warmup_steps = warmup_steps

  def __call__(self, step):
    arg1 = tf.math.rsqrt(step)
    arg2 = step * (self.warmup_steps**-1.5)

    return tf.math.rsqrt(self.d_model) * tf.math.minimum(arg1, arg2)

### Compile Model

In [ ]:
learning_rate = CustomSchedule(D_MODEL)

optimizer = tf.keras.optimizers.Adam(
    learning_rate, beta_1=0.9, beta_2=0.98, epsilon=1e-9)

def accuracy(y_true, y_pred):
  # ensure labels have shape (batch_size, MAX_LENGTH - 1)
  y_true = tf.reshape(y_true, shape=(-1, max_sequences))
  return tf.keras.metrics.sparse_categorical_accuracy(y_true, y_pred)

model.compile(optimizer=optimizer, loss=loss_function, metrics=[accuracy])

## Train

In [ ]:
model.fit(dataset, epochs=EPOCHS)

Epoch 1/50
115/115 [==============================] - 7s 64ms/step - loss: 1.9702 - accuracy: 0.0223
Epoch 2/50
115/115 [==============================] - 8s 66ms/step - loss: 1.7318 - accuracy: 0.0334
Epoch 3/50
115/115 [==============================] - 7s 64ms/step - loss: 1.4763 - accuracy: 0.0423
Epoch 4/50
115/115 [==============================] - 7s 64ms/step - loss: 1.3232 - accuracy: 0.0459
Epoch 5/50
115/115 [==============================] - 7s 64ms/step - loss: 1.2270 - accuracy: 0.0572
Epoch 6/50
115/115 [==============================] - 7s 65ms/step - loss: 1.1367 - accuracy: 0.0677
Epoch 7/50
115/115 [==============================] - 7s 64ms/step - loss: 1.0552 - accuracy: 0.0753
Epoch 8/50
115/115 [==============================] - 7s 64ms/step - loss: 0.9846 - accuracy: 0.0819
Epoch 9/50
115/115 [==============================] - 7s 64ms/step - loss: 0.9222 - accuracy: 0.0871
Epoch 10/50
115/115 [==============================] - 7s 65ms/step - loss: 0.8641 - accura

## Category Classification

In [ ]:
main = wear_data['MAIN']
category = wear_data['CATEGORY']
all_stc = wear_data['SENTENCE']

category_info = pd.DataFrame({"stc":all_stc, "cate":main})
rough_info = pd.DataFrame({"stc":all_stc, "cate":category})

In [ ]:
category_info.dropna(inplace = True)
category_info.reset_index(drop=True, inplace = True)

rough_info.dropna(inplace = True)
rough_info.reset_index(drop=True, inplace = True)

print(category_info.shape, rough_info.shape)

(15725, 2) (15826, 2)


In [ ]:
def make_tokenize(info):
    tagger = Okt()

    for i in range(info.shape[0]):
        info['stc'][i] = tagger.morphs(info['stc'][i])

make_tokenize(category_info)
make_tokenize(rough_info)

In [ ]:
category_list = pd.factorize(category_info['cate'])[1]
category_info['cate'] = pd.factorize(category_info['cate'])[0]

rough_category_list = pd.factorize(rough_info['cate'])[1]
rough_info['cate'] = pd.factorize(rough_info['cate'])[0]

In [ ]:
rough_info['cate']

0        0
1        0
2        0
3        0
4        0
        ..
15821    2
15822    2
15823    2
15824    2
15825    2
Name: cate, Length: 15826, dtype: int64

In [ ]:
from tensorflow.keras.utils import to_categorical
category_ans = to_categorical(category_info['cate']) # 카테고리 관련 원핫벡터 카테고리
rough_ans = to_categorical(rough_info['cate']) # 4개 카테고리 관련 원핫벡터 카테고리

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

ctokenizer = Tokenizer(5000) 
ctokenizer.fit_on_texts(category_info['stc'])
ctoken_stc = ctokenizer.texts_to_sequences(category_info['stc'])
category_stc = ctoken_stc

rtokenizer = Tokenizer(5000) 
rtokenizer.fit_on_texts(rough_info['stc'])
rtoken_stc = rtokenizer.texts_to_sequences(rough_info['stc'])
rough_stc = rtoken_stc

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 15
category_stc = pad_sequences(category_stc, maxlen=max_len) # 카테고리 관련 패딩까지 마친 문장 모음
rough_stc = pad_sequences(rough_stc, maxlen=max_len) # 4개 카테고리 관련 패딩까지 마친 문장 모음

In [ ]:
from sklearn.model_selection import train_test_split

cX_train, cX_test, cy_train, cy_test = train_test_split(
    category_stc, category_ans, test_size = 0.2, shuffle = True, random_state = 11)

rX_train, rX_test, ry_train, ry_test = train_test_split(
    rough_stc, rough_ans, test_size = 0.2, shuffle = True, random_state = 11)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

cmodel = Sequential()
cmodel.add(Embedding(5000, 128))
cmodel.add(LSTM(128))
cmodel.add(Dense(405, activation='softmax'))

rmodel = Sequential()
rmodel.add(Embedding(5000, 100))
rmodel.add(LSTM(128))
rmodel.add(Dense(4, activation='softmax'))

In [ ]:
cmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
cmodel.fit(cX_train, cy_train, validation_data=(cX_test, cy_test), batch_size=32, epochs=30) # 128 64 32 실험

In [ ]:
rmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
rmodel.fit(rX_train, ry_train, validation_data=(rX_test, ry_test), batch_size=10, epochs=10) # 128 64 32 실험

In [ ]:
def find_category(stc,tokenizer,model,category_list):
    tagger = Okt()
    stc = tagger.morphs(stc)
    encode_stc = tokenizer.texts_to_sequences([stc])
    pad_stc = pad_sequences(encode_stc, maxlen=15)
    score = model.predict(pad_stc)
    return (category_list[score.argmax()], score[0, score.argmax()])

In [ ]:
sentence = "이 코트에 어울리는 치마 있나요?"
print(find_category(sentence,ctokenizer,cmodel,category_list))
sentence = "같은 디자인으로 혹시 더 저렴한 상품 있나요?"
print(find_category(sentence,ctokenizer,cmodel,category_list))
sentence = "겨울이니까 좀 길게 입으셔야죠"
print(find_category(sentence,ctokenizer,cmodel,category_list))

In [ ]:
sentence = "이 코트에 어울리는 치마 있나요?"
print(find_category(sentence,rtokenizer,rmodel,rough_category_list))
sentence = "굽 좀 높은 거 없나요?"
print(find_category(sentence,rtokenizer,rmodel,rough_category_list))
sentence = "겨울이니까 좀 길게 입으셔야죠"
print(find_category(sentence,rtokenizer,rmodel,rough_category_list))
sentence = "순금으로 된 제품인가요?"
print(find_category(sentence,rtokenizer,rmodel,rough_category_list))
sentence = "이 제품 얼마인가요?"
print(find_category(sentence,rtokenizer,rmodel,rough_category_list))

In [ ]:
rX_train, rX_test, ry_train, ry_test = train_test_split(
    rough_stc, rough_info['cate'], test_size = 0.2, shuffle = True, random_state = 11)

In [ ]:
tmpX = np.array(rX_train)
tmpX_test = np.array(rX_test)
tmpy = np.array(ry_train)
tmpy_test = np.array(ry_test)

In [ ]:
from sklearn.svm import SVC
# 1000 0.01-> 0.4
# 100 0.01 -> 0.4
# 1 0.01 -> 0.4
# 0.1 0.01 -> 0.38 테케도 못맞춤
# 1 1 -> 0.39
# 100 1 -> 0.38
# 1000 10 -> 0.39
# 1000 1 -> 0.39
maxC = 0
maxG = 0
maxJ = 0
jungdo = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
for i in jungdo:
    for j in jungdo:
        model_svm = SVC(C=i, gamma=j).fit(tmpX, tmpy)
        if(maxJ < model_svm.score(tmpX_test, tmpy_test)):
            maxJ = model_svm.score(tmpX_test, tmpy_test)
            maxC = i
            maxG = j
        print(i,j)

print(maxC, maxG, maxJ)
# model_svm = SVC(C=1000, gamma=1000).fit(tmpX, tmpy)

        # 평가
# print("훈련 세트 정확도: {:.2f}".format(model_svm.score(tmpX, tmpy)))
# print("테스트 세트 정확도: {:.2f}".format(model_svm.score(tmpX_test, tmpy_test)))

0.001 0.001
0.001 0.01
0.001 0.1
0.001 1
0.001 10
0.001 100
0.001 100
0.001 1000
0.01 0.001
0.01 0.01
0.01 0.1
0.01 1
0.01 10
0.01 100
0.01 100
0.01 1000
0.1 0.001
0.1 0.01
0.1 0.1
0.1 1
0.1 10
0.1 100
0.1 100
0.1 1000
1 0.001
1 0.01
1 0.1
1 1
1 10
1 100
1 100
1 1000
10 0.001
10 0.01
10 0.1
10 1
10 10
10 100
10 100
10 1000
100 0.001
100 0.01
100 0.1
100 1
100 10
100 100
100 100
100 1000
100 0.001
100 0.01
100 0.1
100 1
100 10
100 100
100 100
100 1000
1000 0.001
1000 0.01
1000 0.1
1000 1
1000 10
1000 100
1000 100
1000 1000
1 0.001 0.40271636133922933


In [ ]:
model_svm = SVC(C=1, gamma=0.001).fit(tmpX, tmpy)

        # 평가
print("훈련 세트 정확도: {:.2f}".format(model_svm.score(tmpX, tmpy)))
print("테스트 세트 정확도: {:.2f}".format(model_svm.score(tmpX_test, tmpy_test)))

훈련 세트 정확도: 0.90
테스트 세트 정확도: 0.40


In [ ]:
tmpy_test

array([2, 3, 3, ..., 0, 3, 3])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

# 모델 학습
# model = AdaBoostClassifier(n_estimators=5, random_state=42)
# model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
model = DecisionTreeClassifier(max_depth = 5)
model.fit(tmpX, tmpy)

# 평가
# print("훈련 세트 정확도: {:.3f}".format(model.score(tmpX, tmpy)))
print("테스트 세트 정확도: {:.3f}".format(model.score(tmpX_test, tmpX_test)))

ValueError: ignored

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(random_state=42)
model.fit(tmpX, tmpy)

# 평가
print("훈련 세트 정확도: {:.3f}".format(model.score(tmpX, tmpy)))
print("테스트 세트 정확도: {:.3f}".format(model.score(tmpX_test, tmpX_test)))

훈련 세트 정확도: 0.511


ValueError: ignored

## Predict

In [ ]:
# 인덱스를 문장으로 변환
def convert_index_to_text(indexs, vocabulary): 
    
    sentence = ''
    
    # 모든 문장에 대해서 반복
    for index in indexs:
        if index == END_INDEX:
            # 종료 인덱스면 중지
            break;
        if vocabulary.get(index) is not None:
            # 사전에 있는 인덱스면 해당 단어를 추가
            sentence += vocabulary[index]
        else:
            # 사전에 없는 인덱스면 OOV 단어를 추가
            sentence.extend([vocabulary[OOV_INDEX]])
            
        # 빈칸 추가
        sentence += ' '

    return sentence

In [ ]:
# 예측을 위한 입력 생성
def make_predict_input(sentence):

    sentences = []
    sentences.append(sentence)
    sentences = pos_tag(sentences)
    input_seq = convert_text_to_index(sentences, word_to_index, ENCODER_INPUT)
    
    return input_seq

In [ ]:
def evaluate(input_seq):

  input_seq = input_seq.squeeze()
  sentence = tf.expand_dims(input_seq, axis=0)
  output = tf.expand_dims([1], 0)

  for i in range(max_sequences):
    predictions = model(inputs=[sentence, output], training=False)

    # select the last word from the seq_len dimension
    predictions = predictions[:, -1:, :]
    predicted_id = tf.cast(tf.argmax(predictions, axis=-1), tf.int32)

    # return the result if the predicted_id is equal to the end token
    if tf.equal(predicted_id, 2):
      break

    # concatenated the predicted_id to the output which is given to the decoder
    # as its input.
    output = tf.concat([output, predicted_id], axis=-1)

  return tf.squeeze(output, axis=0)

In [ ]:
tmp_test_stc = convert_index_to_text(evaluate(make_predict_input('내일 뭐해요?')).numpy()[1:],index_to_word)
print(tmp_test_stc)
print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))

내일 은 문 닫아요 
('공휴일영업문의', 0.9520013)
('액세서리', 0.7485255)


In [ ]:
tmp_test_stc = convert_index_to_text(evaluate(make_predict_input('이거 사이즈 큰거 있어요?')).numpy()[1:],index_to_word)
print(tmp_test_stc)
print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))

아니요 여기 서 또 할인 되세요 
('구매제품할인문의', 0.36791855)
('의류', 0.56272423)


In [ ]:
tmp_test_stc = convert_index_to_text(evaluate(make_predict_input('이거 사이즈 230 있어요?')).numpy()[1:],index_to_word)
print(tmp_test_stc)
print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))

아니요 프리 사이즈 예요 
('치수문의', 0.99659)
('의류', 0.9994836)


In [ ]:
tmp_test_stc = convert_index_to_text(evaluate(make_predict_input('할인 되요?')).numpy()[1:],index_to_word)
print(tmp_test_stc)
print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))

전 제품 세 일 기간 이라 할인 가능합니다 
('할인여부문의', 0.8501277)
('의류', 0.38548493)


In [ ]:
# for train data predict
for seq_index in range(0,10):

  print("고객 : ",question[seq_index])
  print(find_category(question[seq_index],ctokenizer,cmodel,category_list))
  print(find_category(question[seq_index],rtokenizer,rmodel,rough_category_list))
  print("정답점원 :",answer[seq_index])
  print(find_category(answer[seq_index],ctokenizer,cmodel,category_list))
  print(find_category(answer[seq_index],rtokenizer,rmodel,rough_category_list))
  print("AI점원 :",convert_index_to_text(evaluate(make_predict_input(question[seq_index])).numpy()[1:],index_to_word))
  print(find_category(convert_index_to_text(evaluate(make_predict_input(question[seq_index])).numpy()[1:],index_to_word),ctokenizer,cmodel,category_list))
  print(find_category(convert_index_to_text(evaluate(make_predict_input(question[seq_index])).numpy()[1:],index_to_word),rtokenizer,rmodel,rough_category_list))
  print("\n")

고객 :  신발 은 여기 있는 게 다예 요 ?
('종류별신발제품문의요청', 0.9467577)
('신발', 0.99834406)
정답점원 : 네 성인 이나 아동 다 있어요 발 사이즈 몇 신으세요 ?
('종류별신발제품문의요청', 0.9994634)
('신발', 0.99467564)
AI점원 : 네 , 그거 는 검정색 하나 에요 
('동제품타색상문의', 0.51743716)
('신발', 0.8278762)


고객 :  230 이요
('종류별신발제품문의요청', 0.9270687)
('신발', 0.9999192)
정답점원 : 편하게 신 을 수 있는 거 찾으세요 ?
('착화감', 0.94413644)
('신발', 0.9954848)
AI점원 : 이 신발 신어 보시겠어요 ? 
('종류별신발제품문의요청', 0.85774106)
('신발', 0.99987257)


고객 :  네 봄 이니까 편하게 신 을 수 있는 거
('착화감', 0.9897278)
('신발', 0.99729437)
정답점원 : 이런 건 어떠세요 ? 이런 거도 신발 무척 편하거든요
('의상과코디할제품문의', 0.55929387)
('신발', 0.9998684)
AI점원 : 이런 건 어떠세요 ? 이런 거도 신발 무척 편하거든요 
('의상과코디할제품문의', 0.55929387)
('신발', 0.9998684)


고객 :  굽 좀 높은 거 없나요 ?
('굽높이문의', 0.98385495)
('신발', 0.9999933)
정답점원 : 봄 상품 은 아직 어른 제품 이 많이 안 나왔습니다
('굽높이문의', 0.9914833)
('신발', 0.9941881)
AI점원 : 봄 상품 은 아직 어른 제품 이 많이 안 나왔습니다 
('굽높이문의', 0.9914833)
('신발', 0.9941881)


고객 :  언제 들어와요 ?
('재입고문의', 0.98333675)
('신발', 0.37694752)
정답점원 : 이번 주 지나면 들어올 거 예요
('재입고문의', 0.98705786)
('신발', 0.9583851)
AI점

In [ ]:
tmp_of_all = '안녕하세요'
# tmp_test_stc = convert_index_to_text(evaluate(make_predict_input(tmp_of_all)).numpy()[1:],index_to_word)
print(tmp_of_all)
print(find_category(tmp_of_all,ctokenizer,cmodel,category_list))
print(find_category(tmp_of_all,rtokenizer,rmodel,rough_category_list))

안녕하세요
('결제요청', 0.17259958)
('신발', 0.98255193)


In [ ]:
tmp_test_stc = convert_index_to_text(evaluate(make_predict_input('할인 되요?')).numpy()[1:],index_to_word)
print(tmp_test_stc)
print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))

In [ ]:

question_list1 = ['근무하신지 얼마나 되셨어요?','이가게 월세가 얼마에요?','내일 저랑 데이트 하실래요?','여기 화장실이 어디에요?','이 가방 최대 몇 리터까지 들어갈까요?','이거 끈은 분리하고 세탁기에 돌려야 하나요?','이거 방수 되는 거죠?','우리 애가 이번에 초등학교 들어가는데 가방 추천좀 해주세요.','내구성 좋은 가방은 요즘 어떤게 잘나가요?']
question_list2 = ['이 라이더 자켓 어제 샀는데 영수증 없어도 환불 되나요?','가볍고 따뜻한 패딩조끼 있나요?,물 잘 안빠지는 청바지 있나요?','이 스웨터 여기 살짝 올이 나갔는데 할인 안해주시나요?','가게 앞 마네킹에 피팅된 바지 다른 색깔 있나요?,수선 맡기고 옷 택배로 받아 볼 수 있나요?','지역상품권 결제 가능한가요?','카운터에 있는 점원이 입고 있는 옷 맘에 드는데 어떤 제품인가요?','소개팅에 입고 나갈만한 옷 추천 가능한가요?','이 가게 단골이고 사장님이랑 잘 아는데 현금 결제하면 할인 없나요?']
question_list3= ['침은 모두 알러지 방지 침인가요?','로즈골드 색상도 있나요?','귀걸이는 어떻게 관리해야 하나요?','요즘 잘나가는 제품은 뭔가요?,이 목걸이랑 세트인 귀걸이도 있나요?']
question_list4= ['신어보고 구매 가능할까요?','겨울에 신기는 너무 춥죠?','밖에 날씨가 너무 춥네요','신발이 너무 가벼운거같아요 좀 무게감있는건 없나요?','다른브랜드에서는 비슷한게있나요?']
input_list_all = ['근무하신지 얼마나 되셨어요?','이가게 월세가 얼마에요?','내일 저랑 데이트 하실래요?','여기 화장실이 어디에요?',
                  '이 가방 최대 몇 리터까지 들어갈까요?','이거 끈은 분리하고 세탁기에 돌려야 하나요?',
                  '이거 방수 되는 거죠?','우리 애가 이번에 초등학교 들어가는데 가방 추천좀 해주세요.',
                  '내구성 좋은 가방은 요즘 어떤게 잘나가요?','이 라이더 자켓 어제 샀는데 영수증 없어도 환불 되나요?',
                  '가볍고 따뜻한 패딩조끼 있나요?','물 잘 안빠지는 청바지 있나요?','이 스웨터 여기 살짝 올이 나갔는데 할인 안해주시나요?',
                  '가게 앞 마네킹에 피팅된 바지 다른 색깔 있나요?','수선 맡기고 옷 택배로 받아 볼 수 있나요?','지역상품권 결제 가능한가요?',
                  '카운터에 있는 점원이 입고 있는 옷 맘에 드는데 어떤 제품인가요?','소개팅에 입고 나갈만한 옷 추천 가능한가요?',
                  '이 가게 단골이고 사장님이랑 잘 아는데 현금 결제하면 할인 없나요?','침은 모두 알러지 방지 침인가요??',
                  '로즈골드 색상도 있나요?','귀걸이는 어떻게 관리해야 하나요?','요즘 잘나가는 제품은 뭔가요?',
                  '이 목걸이랑 세트인 귀걸이도 있나요?']
question_list = [question_list1,question_list2,question_list3,question_list4]

percent = 0

for j in question_list:
    for i in j:
        tmp_test_stc = convert_index_to_text(evaluate(make_predict_input(i)).numpy()[1:],index_to_word)
        print(i)
        print(find_category(i,ctokenizer,cmodel,category_list))
        print(find_category(i,rtokenizer,rmodel,rough_category_list))
        print(tmp_test_stc)
        print(find_category(tmp_test_stc,ctokenizer,cmodel,category_list))
        print(find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list))
        if(find_category(i,rtokenizer,rmodel,rough_category_list)[0] == find_category(tmp_test_stc,rtokenizer,rmodel,rough_category_list)[0] ):
            percent+=1
        print()

    print()
    print()
print(percent)

근무하신지 얼마나 되셨어요?
('영업기간문의', 0.8513088)
('신발', 0.99740547)
여기 온 지는 삼 년 됐어요 
('운영기간문의', 0.99351877)
('가방', 0.9960478)

이가게 월세가 얼마에요?
('신발과관련된MD구매', 0.5846967)
('가방', 0.49484193)
오십 프로 해서 육만 구천 원 이에요 
('제품가격문의', 0.99708897)
('가방', 0.8043634)

내일 저랑 데이트 하실래요?
('시즌별카탈로그요구', 0.207884)
('가방', 0.38008243)
네 
('제품가격문의', 0.06582175)
('의류', 0.423783)

여기 화장실이 어디에요?
('화장실위치문의', 0.99481344)
('의류', 0.69682735)
여기 밖에 있어요 
('화장실위치문의', 0.88811153)
('의류', 0.43634188)

이 가방 최대 몇 리터까지 들어갈까요?
('제품사용방법문의', 0.47253865)
('가방', 0.9998165)
이 가방 은 14만 8천 원 이에요 
('제품가격문의', 0.99776065)
('가방', 0.99896693)

이거 끈은 분리하고 세탁기에 돌려야 하나요?
('가방끈문의', 0.39510274)
('신발', 0.61759657)
네 , 우리 옷 는 약간 디자인 옷 들 이에요 
('수제화문의', 0.23560458)
('의류', 0.9999964)

이거 방수 되는 거죠?
('방수제품문의', 0.9986099)
('가방', 0.9992785)
네 
('제품가격문의', 0.06582175)
('의류', 0.423783)

우리 애가 이번에 초등학교 들어가는데 가방 추천좀 해주세요.
('선물할대상에따른제품문의', 0.38436836)
('가방', 0.9993686)
사이즈 가 어떻게 되시나요 ? 
('매장에서착용문의', 0.24881357)
('신발', 0.67877084)

내구성 좋은 가방은 요즘 어떤게 잘나가요?
('유사제품추천요청', 0.867

## Test data prediction
 - 문장중 14900행부터의 문장 100개에 대한 예측.

In [ ]:
test_question_arr = []
test_question = ""

for i in range(14900,wear_data.shape[0]):
        test_question = wear_data.iloc[i].SENTENCE
        test_question_arr.append(test_question)

# test_question_arr = pos_tag(test_question_arr)

In [ ]:
# for train data predict
for seq_index in range(0,10):

  print("고객 : ",test_question_arr[seq_index])
  print(find_category(test_question_arr[seq_index],ctokenizer,cmodel,category_list))
  print(find_category(test_question_arr[seq_index],rtokenizer,rmodel,rough_category_list))
  print("AI점원 :",convert_index_to_text(evaluate(make_predict_input(test_question_arr[seq_index])).numpy()[1:],index_to_word))
  print(find_category(convert_index_to_text(evaluate(make_predict_input(test_question_arr[seq_index])).numpy()[1:],index_to_word),ctokenizer,cmodel,category_list))
  print(find_category(convert_index_to_text(evaluate(make_predict_input(test_question_arr[seq_index])).numpy()[1:],index_to_word),rtokenizer,rmodel,rough_category_list))
  print("\n")

고객 :  구제는 뭐예요?
('신제품,구제품관련문의', 0.99233705)
('의류', 0.99975735)
AI점원 : 예 
('원하는제품재고여부확인', 0.120788075)
('가방', 0.471872)


고객 :  구제 옷도 있네요?
('신제품,구제품관련문의', 0.99220467)
('의류', 0.99997735)
AI점원 : 예 , 그 옷 은 봄 옷 이 전부 에요 
('계절상품문의', 0.3881231)
('의류', 0.99920744)


고객 :  구제품은 다 세탁해서 나온 거예요?
('구제품세탁여부문의', 0.9989729)
('의류', 0.99877924)
AI점원 : 네 고객 님 께 저 제품 소재 가 요즘 에는 아이보리 가 낫고요 
('제품특징문의', 0.6134685)
('신발', 0.96028894)


고객 :  이건 다 세탁이 된 거죠?
('구제품세탁여부문의', 0.973141)
('의류', 0.9701384)
AI점원 : 네 
('가방소재문의', 0.054704018)
('의류', 0.42276567)


고객 :  구제품은 세탁해서 파시는 건가요?
('구제품세탁여부문의', 0.99079835)
('의류', 0.9975472)
AI점원 : 네 고객 님 팔고 있습니다 
('운동종목별기능성제품문의', 0.8318357)
('액세서리', 0.9776799)


고객 :  구제품은 다 세탁해서 나오는 거겠죠?
('구제품세탁여부문의', 0.9833261)
('의류', 0.99890816)
AI점원 : 네 고객 님 이 제품 이 잘 나가요 
('베스트상품문의', 0.6179648)
('가방', 0.45370793)


고객 :  카드로 결제하면 부가세 별도에요?
('카드결제부가세여부문의', 0.99447745)
('의류', 0.93950886)
AI점원 : 카드 결제 해도 똑같은 가격 이에요 
('현금할인가문의', 0.93692863)
('의류', 0.9871682)


고객 :  카드는 부가세 별도로 붙나요?
('카드결제부가세여부문의', 