<a href="https://colab.research.google.com/github/ideablast/NLPer_chatbot/blob/kdg/Seq2Seq_Chatbot_%EC%9D%98%EB%A5%98_Okt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Below is for mecab and konlpy error handling
 - download mecab-ko
 - download m4, autoconf, automake
 - downoad mecab-ko-dic
 - error handling download mecab-ko-dic
 - download mecab-python3

In [1]:
import os
os.chdir('/tmp/')
!curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz #check latest version by https://bitbucket.org/eunjeon/mecab-ko/downloads/
!tar zxfv mecab-0.996-ko-0.9.2.tar.gz
os.chdir('/tmp/mecab-0.996-ko-0.9.2')
!./configure
!make
!make check
!make install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1381k  100 1381k    0     0  1010k      0  0:00:01  0:00:01 --:--:--  177M
mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/con

In [2]:
os.chdir('/tmp/')

!wget -O m4-latest.tar.gz http://ftp.gnu.org/gnu/m4/m4-latest.tar.gz
!tar -zvxf m4-latest.tar.gz
os.chdir('/tmp/m4-1.4.17') # it can be changed.
!./configure
!make
!make install

os.chdir('/tmp')
!curl -OL http://ftpmirror.gnu.org/autoconf/autoconf-latest.tar.gz
!tar xzf autoconf-latest.tar.gz
os.chdir('/tmp/autoconf-2.69')
!./configure --prefix=/usr/local
!make
!make install
!export PATH=/usr/local/bin

--2020-10-29 01:51:35--  http://ftp.gnu.org/gnu/m4/m4-latest.tar.gz
Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1820658 (1.7M) [application/x-gzip]
Saving to: ‘m4-latest.tar.gz’

m4-latest.tar.gz    100%[===================>]   1.74M  2.96MB/s    in 0.6s    

2020-10-29 01:51:36 (2.96 MB/s) - ‘m4-latest.tar.gz’ saved [1820658/1820658]

m4-1.4.17/
m4-1.4.17/.prev-version
m4-1.4.17/.tarball-version
m4-1.4.17/.version
m4-1.4.17/acinclude.m4
m4-1.4.17/aclocal.m4
m4-1.4.17/AUTHORS
m4-1.4.17/BACKLOG
m4-1.4.17/bootstrap
m4-1.4.17/build-aux/
m4-1.4.17/c-boxes.el
m4-1.4.17/cfg.mk
m4-1.4.17/ChangeLog
m4-1.4.17/checks/
m4-1.4.17/configure
m4-1.4.17/configure.ac
m4-1.4.17/COPYING
m4-1.4.17/doc/
m4-1.4.17/examples/
m4-1.4.17/GNUmakefile
m4-1.4.17/INSTALL
m4-1.4.17/lib/
m4-1.4.17/m4/
m4-1.4.17/maint.mk
m4-1.4.17/Makefile.am
m4-1.4.17/Makefile.in
m

In [3]:
os.chdir('/tmp')
!curl -LO http://ftpmirror.gnu.org/automake/automake-1.9.tar.gz # checck latest version http://ftpmirror.gnu.org/automake/
!tar -zxvf automake-1.9.tar.gz
os.chdir('/tmp/automake-1.9')
!./configure
!make
!make install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  884k  100  884k    0     0   588k      0  0:00:01  0:00:01 --:--:-- 1283k
automake-1.9/
automake-1.9/m4/
automake-1.9/m4/amversion.m4
automake-1.9/m4/auxdir.m4
automake-1.9/m4/init.m4
automake-1.9/m4/install-sh.m4
automake-1.9/m4/lead-dot.m4
automake-1.9/m4/missing.m4
automake-1.9/m4/mkdirp.m4
automake-1.9/m4/options.m4
automake-1.9/m4/runlog.m4
automake-1.9/m4/sanity.m4
automake-1.9/m4/strip.m4
automake-1.9/m4/tar.m4
automake-1.9/m4/as.m4
automake-1.9/m4/ccstdc.m4
automake-1.9/m4/cond.m4
automake-1.9/m4/depend.m4
automake-1.9/m4/depout.m4
automake-1.9/m4/dmalloc.m4
automake-1.9/m4/gcj.m4
automake-1.9/m4/header.m4
automake-1.9/m4/lex.m4
automake-1.9/m4/lispdir.m4
automake-1.9/m4/maintainer.m4
automake-1.9/m4/make.m4
automake-1.9/m4/minuso.m4
automa

In [4]:
os.chdir('/tmp')
!curl -LO https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz #check latest version by https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/
!tar -zxvf mecab-ko-dic-2.1.1-20180720.tar.gz
os.chdir('/tmp/mecab-ko-dic-2.1.1-20180720')
!./autogen.sh
!./configure
!make
# !sh -c 'echo "dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic" > /usr/local/etc/mecabrc'
!make install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47.4M  100 47.4M    0     0  17.2M      0  0:00:02  0:00:02 --:--:-- 29.1M
mecab-ko-dic-2.1.1-20180720/
mecab-ko-dic-2.1.1-20180720/configure
mecab-ko-dic-2.1.1-20180720/COPYING
mecab-ko-dic-2.1.1-20180720/autogen.sh
mecab-ko-dic-2.1.1-20180720/Place-station.csv
mecab-ko-dic-2.1.1-20180720/NNG.csv
mecab-ko-dic-2.1.1-20180720/README
mecab-ko-dic-2.1.1-20180720/EF.csv
mecab-ko-dic-2.1.1-20180720/MAG.csv
mecab-ko-dic-2.1.1-20180720/Preanalysis.csv
mecab-ko-dic-2.1.1-20180720/NNB.csv
mecab-ko-dic-2.1.1-20180720/Person-actor.csv
mecab-ko-dic-2.1.1-20180720/VV.csv
mecab-ko-dic-2.1.1-20180720/Makefile.in
mecab-ko-dic-2.1.1-20180720/matrix.def
mecab-ko-dic-2.1.1-20180720/EC.csv
mecab-ko-dic-2.1.1-20180720/NNBC.csv
mecab-ko-dic-2.1.1-20180720/clean
mecab-ko-

In [5]:
# if above cell error 'make: *** [model.bin] Error 127' execute this cell and excute above cell again
os.chdir('/tmp/mecab-ko-dic-2.1.1-20180720')
!ldconfig
!ldconfig -p | grep /usr/local/lib

/sbin/ldconfig.real: /usr/local/lib/python3.6/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

	libmklml_intel.so (libc6,x86-64) => /usr/local/lib/python3.6/dist-packages/ideep4py/lib/libmklml_intel.so
	libmkldnn.so.0 (libc6,x86-64) => /usr/local/lib/python3.6/dist-packages/ideep4py/lib/libmkldnn.so.0
	libmkl_vml_mc3.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_mc3.so
	libmkl_vml_mc2.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_mc2.so
	libmkl_vml_mc.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_mc.so
	libmkl_vml_def.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_def.so
	libmkl_vml_cmpt.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_cmpt.so
	libmkl_vml_avx512_mic.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_avx512_mic.so
	libmkl_vml_avx512.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_avx512.so
	libmkl_vml_avx2.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_avx2.so
	libmkl_vml_avx.so (libc6,x86-64) => /usr/local/lib/libmkl_vml_avx.so
	libmkl_tbb_thread.so (libc6

In [6]:
os.chdir('/tmp')
!curl -LO https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz #check latest version by https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/
!tar -zxvf mecab-ko-dic-2.1.1-20180720.tar.gz
os.chdir('/tmp/mecab-ko-dic-2.1.1-20180720')
!./autogen.sh
!./configure
!make
# !sh -c 'echo "dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic" > /usr/local/etc/mecabrc'
!make install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47.4M  100 47.4M    0     0  17.1M      0  0:00:02  0:00:02 --:--:-- 22.7M
mecab-ko-dic-2.1.1-20180720/
mecab-ko-dic-2.1.1-20180720/configure
mecab-ko-dic-2.1.1-20180720/COPYING
mecab-ko-dic-2.1.1-20180720/autogen.sh
mecab-ko-dic-2.1.1-20180720/Place-station.csv
mecab-ko-dic-2.1.1-20180720/NNG.csv
mecab-ko-dic-2.1.1-20180720/README
mecab-ko-dic-2.1.1-20180720/EF.csv
mecab-ko-dic-2.1.1-20180720/MAG.csv
mecab-ko-dic-2.1.1-20180720/Preanalysis.csv
mecab-ko-dic-2.1.1-20180720/NNB.csv
mecab-ko-dic-2.1.1-20180720/Person-actor.csv
mecab-ko-dic-2.1.1-20180720/VV.csv
mecab-ko-dic-2.1.1-20180720/Makefile.in
mecab-ko-dic-2.1.1-20180720/matrix.def
mecab-ko-dic-2.1.1-20180720/EC.csv
mecab-ko-dic-2.1.1-20180720/NNBC.csv
mecab-ko-dic-2.1.1-20180720/clean
mecab-ko-

In [7]:
!pip install mecab-python3

     |████████████████████████████████| 3.5MB 8.6MB/s 


In [8]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
%cd Mecab-ko-for-Google-Colab
!bash install_mecab-ko_on_colab190912.sh

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 60 (delta 23), reused 20 (delta 5), pack-reused 0
Unpacking objects: 100% (60/60), done.
/tmp/mecab-ko-dic-2.1.1-20180720/Mecab-ko-for-Google-Colab
Installing konlpy.....
     |████████████████████████████████| 19.4MB 169kB/s 
     |████████████████████████████████| 460kB 47.2MB/s 
     |████████████████████████████████| 92kB 10.8MB/s 
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2020-10-29 01:53:10--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mec

In [9]:
!pip install konlpy

## Import

In [10]:
from keras import models
from keras import layers
from keras import optimizers, losses, metrics
from keras import preprocessing

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt,Hannanum,Kkma,Komoran,Mecab

## Hyperparameter

In [11]:
# 태그 단어
PAD = "<PADDING>"   # 패딩
STA = "<START>"     # 시작
END = "<END>"       # 끝
OOV = "<OOV>"       # 없는 단어(Out of Vocabulary)

# 태그 인덱스
PAD_INDEX = 0
STA_INDEX = 1
END_INDEX = 2
OOV_INDEX = 3

# 데이터 타입
ENCODER_INPUT  = 0
DECODER_INPUT  = 1
DECODER_TARGET = 2

# 한 문장에서 단어 시퀀스의 최대 개수
max_sequences = 30

# 임베딩 벡터 차원
embedding_dim = 100

# LSTM 히든레이어 차원 : 100 이 좋단다.
lstm_hidden_dim = 100

epochs = 50
batch_size = 64

# 정규 표현식 필터
RE_FILTER = re.compile("[\"':;~()]")

## Data Load & Preprocessing

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
wear_data = pd.read_csv("/content/drive/My Drive/wear.csv")
print(wear_data.shape)
customer = wear_data[wear_data.SPEAKER == "고객"].SENTENCE
store = wear_data[wear_data.SPEAKER == "점원"].SENTENCE
print(customer.shape, store.shape) # 질문의 개수와 답의 개수가 일치하지 않는다.

(15826, 20)
(8381,) (7445,)


In [14]:
prev = "고객"
store_arr = []
customer_arr = []
store_stc = ""
customer_stc = ""

for i in range(wear_data.shape[0]):
    if (prev == wear_data.iloc[i].SPEAKER):
        if prev == "점원":
             store_stc += (" "+wear_data.iloc[i].SENTENCE)
        else : 
             customer_stc += (" "+wear_data.iloc[i].SENTENCE)
            
    elif prev == "점원":
        store_arr.append(store_stc)
        customer_stc = wear_data.iloc[i].SENTENCE
        prev = "고객"
    else :
        customer_arr.append(customer_stc)
        store_stc = wear_data.iloc[i].SENTENCE
        prev = "점원"

print(len(store_arr))
print(len(customer_arr))
print(store_arr[-1])
print(customer_arr[-1]) # 자료 상에서 이후에는 계속 고객의 물음만 계속된다. 코드 레벨에서 이 부분은 빼게 구현했다. (stc는 만들어지지만 arr에 append 안하게 된다.)

7301
7301
요즘 파스텔 톤이 유행이에요
요즘 유행하는 색깔이 뭐예요?


In [36]:
question = []
answer = []

for Q in customer_arr:
    question.append(Q.replace("[^\w]", " "))

for A in store_arr:
    answer.append(A.replace("[^\w]", " "))

len(question), len(answer)

(7301, 7301)

In [39]:
# 형태소분석 함수
def pos_tag(sentences):
    
    # KoNLPy 형태소분석기 설정
    tagger = Okt()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in sentences:
        # [\"':;~()] 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [40]:
# 형태소분석 수행
question = pos_tag(question)
answer = pos_tag(answer)

# 형태소분석으로 변환된 챗봇 데이터 출력
for i in range(5):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()


Q : 신발 은 여기 있 는 게 다 예요 ?
A : 네 성인 이나 아동 다 있 어요 발 사이즈 몇 신 으세요 ?

Q : 230 이 요
A : 편하 게 신 을 수 있 는 거 찾 으세요 ?

Q : 네 봄 이 니까 편하 게 신 을 수 있 는 거
A : 이런 건 어떠세요 ? 이런 거 도 신발 무척 편하 거든요

Q : 굽 좀 높 은 거 없 나요 ?
A : 봄 상품 은 아직 어른 제품 이 많이 안 나왔 습니다

Q : 언제 들어와요 ?
A : 이번 주 지 나 면 들어올 거 예요



In [18]:
# 질문과 대답 문장들을 하나로 합침
sentences = []
sentences.extend(question)
sentences.extend(answer)

words = []

# 단어들의 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)

# 길이가 0인 단어는 삭제
words = [word for word in words if len(word) > 0]

# 중복된 단어 삭제
words = list(set(words))

# 제일 앞에 태그 단어 삽입
words[:0] = [PAD, STA, END, OOV]

In [19]:
print("손님과 점원의 말에서 사용된 총 단어의 수 :",len(words))

손님과 점원의 말에서 사용된 총 단어의 수 : 6409


In [20]:
# 단어와 인덱스의 딕셔너리 생성
word_to_index = {word: index for index, word in enumerate(words)}
index_to_word = {index: word for index, word in enumerate(words)}

In [21]:
# 문장을 인덱스로 변환
def convert_text_to_index(sentences, vocabulary, type): 
    
    sentences_index = []
    
    # 모든 문장에 대해서 반복
    for sentence in sentences:
        sentence_index = []
        
        # 디코더 입력일 경우 맨 앞에 START 태그 추가
        if type == DECODER_INPUT:
            sentence_index.extend([vocabulary[STA]])
        
        # 문장의 단어들을 띄어쓰기로 분리
        for word in sentence.split():
            if vocabulary.get(word) is not None:
                # 사전에 있는 단어면 해당 인덱스를 추가
                sentence_index.extend([vocabulary[word]])
            else:
                # 사전에 없는 단어면 OOV 인덱스를 추가
                sentence_index.extend([vocabulary[OOV]])

        # 최대 길이 검사
        if type == DECODER_TARGET:
            # 디코더 목표일 경우 맨 뒤에 END 태그 추가
            if len(sentence_index) >= max_sequences:
                sentence_index = sentence_index[:max_sequences-1] + [vocabulary[END]]
            else:
                sentence_index += [vocabulary[END]]
        else:
            if len(sentence_index) > max_sequences:
                sentence_index = sentence_index[:max_sequences]
            
        # 최대 길이에 없는 공간은 패딩 인덱스로 채움
        sentence_index += (max_sequences - len(sentence_index)) * [vocabulary[PAD]]
        
        # 문장의 인덱스 배열을 추가
        sentences_index.append(sentence_index)

    return np.asarray(sentences_index)

In [22]:
# 인코더 입력 인덱스 변환
x_encoder = convert_text_to_index(question, word_to_index, ENCODER_INPUT)

# 첫 번째 인코더 입력 출력 (신발 은 여기 있는 게 다예 요)
print(question[0])
x_encoder[0]


신발 은 여기 있는 게 다예 요 ?


array([3980, 2643, 2731, 4729, 2018, 3144, 1766, 2900,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [23]:
# 디코더 입력 인덱스 변환
x_decoder = convert_text_to_index(answer, word_to_index, DECODER_INPUT)

# 첫 번째 디코더 입력 출력 (<START> 신발 은 여기 있는 게 다예 요)
print(question[0])
x_decoder[0]


신발 은 여기 있는 게 다예 요 ?


array([   1, 5395, 6165, 3459, 3850,  877, 6092, 4009, 1387, 5379, 4788,
       2900,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [24]:
# 디코더 목표 인덱스 변환
y_decoder = convert_text_to_index(answer, word_to_index, DECODER_TARGET)

# 첫 번째 디코더 입력 출력 (신발 은 여기 있는 게 다예 요 <END>)
print(question[0])
y_decoder[0]


신발 은 여기 있는 게 다예 요 ?


array([5395, 6165, 3459, 3850,  877, 6092, 4009, 1387, 5379, 4788, 2900,
          2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [25]:
# 원핫인코딩 초기화 y_decoder는 원핫인코딩 해줘야 함.
one_hot_data = np.zeros((len(y_decoder), max_sequences, len(words)))

# 디코더 목표를 원핫인코딩으로 변환
# 학습시 입력은 인덱스이지만, 출력은 원핫인코딩 형식임
for i, sequence in enumerate(y_decoder):
    for j, index in enumerate(sequence):
        one_hot_data[i, j, index] = 1

# 디코더 목표 설정
y_decoder = one_hot_data

# 첫 번째 디코더 목표 출력
y_decoder[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

인코더 입력과 디코더 입력은 임베딩 레이어에 들어가는 인덱스 배열입니다. 반면에 디코더 출력은 원핫인코딩 형식이 되어야 합니다. 디코더의 마지막 Dense 레이어에서 softmax로 나오기 때문입니다.

## Attention

In [24]:
# class BahdanauAttention(tf.keras.Model):
#   def __init__(self, units):
#     super(BahdanauAttention, self).__init__()
#     self.W1 = Dense(units)
#     self.W2 = Dense(units)
#     self.V = Dense(1)

#   def call(self, values, query): # 단, key와 value는 같음
#     # query shape == (batch_size, hidden size) : 이전 시점 decoder cell의 hidden state. 루옹버전은 해당 시점.
#     # hidden_with_time_axis shape == (batch_size, 1, hidden size)
#     # score 계산을 위해 뒤에서 할 덧셈을 위해서 차원을 변경해줍니다.
#     hidden_with_time_axis = tf.expand_dims(query, 1)

#     # score shape == (batch_size, max_length, 1)
#     # we get 1 at the last axis because we are applying score to self.V
#     # the shape of the tensor before applying self.V is (batch_size, max_length, units)
#     score = self.V(tf.nn.tanh(
#         self.W1(values) + self.W2(hidden_with_time_axis)))

#     # attention_weights shape == (batch_size, max_length, 1)
#     attention_weights = tf.nn.softmax(score, axis=1)

#     # context_vector shape after sum == (batch_size, hidden_size)
#     context_vector = attention_weights * values
#     context_vector = tf.reduce_sum(context_vector, axis=1)

#     return context_vector, attention_weights

## 모델 생성

In [26]:
#--------------------------------------------
# 훈련 모델 인코더 정의
#--------------------------------------------

# 입력 문장의 인덱스 시퀀스를 입력으로 받음
encoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
encoder_outputs = layers.Embedding(len(words), embedding_dim)(encoder_inputs)

# return_state가 True면 상태값 리턴
# LSTM은 state_h(hidden state)와 state_c(cell state) 2개의 상태 존재
encoder_outputs, state_h, state_c = layers.LSTM(lstm_hidden_dim,
                                                return_state=True)(encoder_outputs)

# 히든 상태와 셀 상태를 하나로 묶음
encoder_states = [state_h, state_c]

#--------------------------------------------
# 훈련 모델 디코더 정의
#--------------------------------------------

# 목표 문장의 인덱스 시퀀스를 입력으로 받음
decoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
decoder_embedding = layers.Embedding(len(words), embedding_dim)
decoder_outputs = decoder_embedding(decoder_inputs)

# 인코더와 달리 return_sequences를 True로 설정하여 모든 타임 스텝 출력값 리턴
# 모든 타임 스텝의 출력값들을 다음 레이어의 Dense()로 처리하기 위함
decoder_lstm = layers.LSTM(lstm_hidden_dim,
                           return_state=True,
                           return_sequences=True)

# initial_state를 인코더의 상태로 초기화
decoder_outputs, _, _ = decoder_lstm(decoder_outputs,
                                     initial_state=encoder_states)

# 단어의 개수만큼 노드의 개수를 설정하여 원핫 형식으로 각 단어 인덱스를 출력
decoder_dense = layers.Dense(len(words), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)



#--------------------------------------------
# 훈련 모델 정의
#--------------------------------------------

# 입력과 출력으로 함수형 API 모델 생성
model = models.Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 학습 방법 설정
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [27]:
#--------------------------------------------
#  예측 모델 인코더 정의
#--------------------------------------------

# 훈련 모델의 인코더 상태를 사용하여 예측 모델 인코더 설정
encoder_model = models.Model(encoder_inputs, encoder_states)

#--------------------------------------------
# 예측 모델 디코더 정의
#--------------------------------------------

# 예측시에는 훈련시와 달리 타임 스텝을 한 단계씩 수행
# 매번 이전 디코더 상태를 입력으로 받아서 새로 설정
decoder_state_input_h = layers.Input(shape=(lstm_hidden_dim,))
decoder_state_input_c = layers.Input(shape=(lstm_hidden_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]    

# 임베딩 레이어
decoder_outputs = decoder_embedding(decoder_inputs)

# LSTM 레이어
decoder_outputs, state_h, state_c = decoder_lstm(decoder_outputs,
                                                 initial_state=decoder_states_inputs)

# 히든 상태와 셀 상태를 하나로 묶음
decoder_states = [state_h, state_c]

# Dense 레이어를 통해 원핫 형식으로 각 단어 인덱스를 출력
decoder_outputs = decoder_dense(decoder_outputs)

# 예측 모델 디코더 설정
decoder_model = models.Model([decoder_inputs] + decoder_states_inputs,
                      [decoder_outputs] + decoder_states)

예측 모델은 이미 학습된 훈련 모델의 레이어들을 그대로 재사용합니다. 예측 모델 인코더는 훈련 모델 인코더과 동일합니다. 그러나 예측 모델 디코더는 매번 LSTM 상태값을 입력으로 받습니다. 또한 디코더의 LSTM 상태를 출력값과 같이 내보내서, 다음 번 입력에 넣습니다. 

이렇게 하는 이유는 LSTM을 딱 한번의 타임 스텝만 실행하기 때문입니다. 그래서 매번 상태값을 새로 초기화 해야 합니다. 이와 반대로 훈련할때는 문장 전체를 계속 LSTM으로 돌리기 때문에 자동으로 상태값이 전달됩니다. 


## Train

In [28]:
# 인덱스를 문장으로 변환
def convert_index_to_text(indexs, vocabulary): 
    
    sentence = ''
    
    # 모든 문장에 대해서 반복
    for index in indexs:
        if index == END_INDEX:
            # 종료 인덱스면 중지
            break;
        if vocabulary.get(index) is not None:
            # 사전에 있는 인덱스면 해당 단어를 추가
            sentence += vocabulary[index]
        else:
            # 사전에 없는 인덱스면 OOV 단어를 추가
            sentence.extend([vocabulary[OOV_INDEX]])
            
        # 빈칸 추가
        sentence += ' '

    return sentence

In [45]:
x_encoder[2]

array([2103,  718, 4415,   75, 4896, 6094,  301, 3898,  273,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [ ]:
x_encoder[2].reshape(1, x_encoder[2].shape[0])

array([[3245, 1886, 6060, 4767, 1496, 5142, 6206,  624, 3873,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]])

In [46]:
input_encoder = x_encoder[2].reshape(1, x_encoder[2].shape[0])
input_decoder = x_decoder[2].reshape(1, x_decoder[2].shape[0])
[input_encoder, input_decoder]

[array([[2103,  718, 4415,   75, 4896, 6094,  301, 3898,  273,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]),
 array([[   1, 4818, 1261, 1519, 3186, 4818, 1327, 4999, 2000, 5675,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]])]

In [29]:
# 에폭 반복
for epoch in range(epochs):
    print('Total Epoch :', epoch + 1)

    # 훈련 시작
    history = model.fit(x = [x_encoder, x_decoder],
                        y = y_decoder,
                        verbose=1,
                        validation_split = 0.1
                        )
    # '신발 은 여기 있는 게 다예 요 ?'에 대한 대답
    # input_encoder = x_encoder[0].reshape(1, x_encoder[0].shape[0])
    # input_decoder = x_decoder[0].reshape(1, x_decoder[0].shape[0])
    # results = model.predict([input_encoder, input_decoder])
    
    # # 결과의 원핫인코딩 형식을 인덱스로 변환
    # # 1축을 기준으로 가장 높은 값의 위치를 구함
    # indexs = np.argmax(results[0], 1)
    
    # # 인덱스를 문장으로 변환
    # sentence = convert_index_to_text(indexs, index_to_word)
    # print(sentence)
    # print()

Total Epoch : 1
206/206 [==============================] - 7s 36ms/step - loss: 1.9701 - accuracy: 0.7795 - val_loss: 1.2755 - val_accuracy: 0.8062
Total Epoch : 2
206/206 [==============================] - 6s 31ms/step - loss: 1.2871 - accuracy: 0.8085 - val_loss: 1.2387 - val_accuracy: 0.8092
Total Epoch : 3
206/206 [==============================] - 6s 30ms/step - loss: 1.2440 - accuracy: 0.8115 - val_loss: 1.2007 - val_accuracy: 0.8152
Total Epoch : 4
206/206 [==============================] - 6s 30ms/step - loss: 1.2054 - accuracy: 0.8161 - val_loss: 1.1664 - val_accuracy: 0.8252
Total Epoch : 5
206/206 [==============================] - 6s 30ms/step - loss: 1.1644 - accuracy: 0.8219 - val_loss: 1.1306 - val_accuracy: 0.8291
Total Epoch : 6
206/206 [==============================] - 6s 31ms/step - loss: 1.1264 - accuracy: 0.8273 - val_loss: 1.1054 - val_accuracy: 0.8306
Total Epoch : 7
206/206 [==============================] - 6s 31ms/step - loss: 1.0943 - accuracy: 0.8315 - val_

In [30]:
# 예측을 위한 입력 생성
def make_predict_input(sentence):

    sentences = []
    sentences.append(sentence)
    sentences = pos_tag(sentences)
    input_seq = convert_text_to_index(sentences, word_to_index, ENCODER_INPUT)
    
    return input_seq

In [31]:
# 텍스트 생성
def generate_text(input_seq):
    
    # 입력을 인코더에 넣어 마지막 상태 구함
    states = encoder_model.predict(input_seq)

    # 목표 시퀀스 초기화
    target_seq = np.zeros((1, 1))
    
    # 목표 시퀀스의 첫 번째에 <START> 태그 추가
    target_seq[0, 0] = STA_INDEX
    
    # 인덱스 초기화
    indexs = []
    
    # 디코더 타임 스텝 반복
    while 1:
        # 디코더로 현재 타임 스텝 출력 구함
        # 처음에는 인코더 상태를, 다음부터 이전 디코더 상태로 초기화
        decoder_outputs, state_h, state_c = decoder_model.predict(
                                                [target_seq] + states)

        # 결과의 원핫인코딩 형식을 인덱스로 변환
        index = np.argmax(decoder_outputs[0, 0, :])
        indexs.append(index)
        
        # 종료 검사
        if index == END_INDEX or len(indexs) >= max_sequences:
            break

        # 목표 시퀀스를 바로 이전의 출력으로 설정
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = index
        
        # 디코더의 이전 상태를 다음 디코더 예측에 사용
        states = [state_h, state_c]

    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
        
    return sentence

In [34]:
# 문장을 인덱스로 변환
input_seq = make_predict_input('교환 가능한가요?')
input_seq


array([[3646, 2898, 2900,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]])

In [35]:
# 예측 모델로 텍스트 생성
sentence = generate_text(input_seq)
sentence


'네 , 가능합니다 . '

In [53]:
# for train data predict
for seq_index in range(0,100):

  print("고객 : ",question[seq_index])
  print("정답점원 :",answer[seq_index])
  print("AI점원 :",generate_text(make_predict_input(question[seq_index])))
  print("\n")

고객 :  신발 은 여기 있는 게 다예 요 ?
정답점원 : 네 성인 이나 아동 다 있어요 발 사이즈 몇 신으세요 ?
AI점원 : 네 이 게 좀 더 좋아요 


고객 :  230 이요
정답점원 : 편하게 신 을 수 있는 거 찾으세요 ?
AI점원 : 네 그럼 이 쪽 에 진열 되어있습니다 


고객 :  네 봄 이니까 편하게 신 을 수 있는 거
정답점원 : 이런 건 어떠세요 ? 이런 거도 신발 무척 편하거든요
AI점원 : 이런 게 잘 나가요 


고객 :  굽 좀 높은 거 없나요 ?
정답점원 : 봄 상품 은 아직 어른 제품 이 많이 안 나왔습니다
AI점원 : 네 있습니다 


고객 :  언제 들어와요 ?
정답점원 : 이번 주 지나면 들어올 거 예요
AI점원 : 다음 주 까지 오시 면 될 거 예요 


고객 :  이 거 는 가죽 이에요 ?
정답점원 : 가죽 아니고 쎄 무예 요
AI점원 : 네 


고객 :  가죽 은 얼마 예요 ?
정답점원 : 2만 9천 원 입니다
AI점원 : 지금 세 일 하 는 3만 원 이요 


고객 :  털 달린 거 저 거 는 사이즈 있어요 ?
정답점원 : 230 이 없어요 이 거 한 번 신어 보세요
AI점원 : 지금 은 이 거 밖에 없어요 


고객 :  좀 크네 또 안 들어와요 ?
정답점원 : 네 이건 다 끝났어요
AI점원 : 네 


고객 :  가방 매는 거 보고 있어요
정답점원 : 여기 있어요
AI점원 : 이 거 는 지금 사이즈 밖에 없어요 


고객 :  가격 이 얼마 예요 ?
정답점원 : 이 종류 는 2만 원 이고 이 종류 는 3만 8천 원 이에요
AI점원 : 이 거 는 3만 원 이요 


고객 :  가죽 으로 된 거 는 없어요 ?
정답점원 : 가죽 은 없고 레자 만 있어요
AI점원 : 네 


고객 :  레자 는 얼마 예요 ?
정답점원 : 5만 5천 원요
AI점원 : 이 거 는 3만 원 이요 


고객 :  이 거 는 천이 죠 ?
정답점원 : 네 맞아요
AI점원 : 네 


고객 :  이건 얼마 예요 ?
정답점원 : 그것 도 5만 5